import "C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\prsht.idl";
import "C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\mshtml.idl";
import "c:\program files (x86)\microsoft visual studio .net 2003\vc7\platformsdk\include\dimm.idl";
import "C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\mshtmhst.idl";
import "c:\program files (x86)\microsoft visual studio .net 2003\vc7\platformsdk\include\docobj.idl";
import "C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\exdisp.idl";
import "C:\Program Files (x86)\Microsoft Visual Studio .NET 2003\Vc7\PlatformSDK\include\objsafe.idl";

[
	object,
	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
	dual,
	helpstring("IComponentRegistrar Interface"),
	pointer_default(unique)
] 
#line 15 "d:\\work\\v1.18\\additional\\sbrf\\autosubscriptions\\activex component for sbrf\\source code dll\\sbrf\\compreg.h"
interface IComponentRegistrar : IDispatch {
#line 17 "d:\\work\\v1.18\\additional\\sbrf\\autosubscriptions\\activex component for sbrf\\source code dll\\sbrf\\compreg.h"
	[id(1)] HRESULT  Attach([in] BSTR bstrPath);
	[id(2)] HRESULT  RegisterAll();
	[id(3)] HRESULT  UnregisterAll();
	[id(4)] HRESULT  GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
	[id(5)] HRESULT  RegisterComponent([in] BSTR bstrCLSID);
	[id(6)] HRESULT  UnregisterComponent([in] BSTR bstrCLSID);
};

[
	object,
	uuid(5537E0C6-5683-49C0-A958-619EFF1301E6),
	dual,
	helpstring("IServer Interface"),
	pointer_default(unique)
] 
#line 17 "d:\\work\\111\\acitvex\\server.h"
interface IServer : IDispatch {
#line 19 "d:\\work\\111\\acitvex\\server.h"
	[id(1),helpstring("method NFun")] HRESULT  NFun([in]LONG func, [out,retval] LONG *result);
	[id(2),helpstring("method GParamString")] HRESULT  GParamString([in]BSTR name, [out,retval] BSTR *value );
	[id(3),helpstring("method SÐaram")] HRESULT  SÐaram([in]BSTR name, [in]BSTR value);
	[id(4),helpstring("method Clear")] HRESULT  Clear();
};


[ version(1.0), uuid(EA8C9799-D0AF-4FD1-92E7-EC4CACD1C535), custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a, "{D9EB58F1-AFDF-45F5-886D-4528B692400F}"), helpstring("SBRF 1.0 Type Library") ]
library SBRF
{
	importlib("stdole2.tlb");
	importlib("olepro32.dll");

	[
		version(1.0),
		uuid(D9EB58F1-AFDF-45F5-886D-4528B692400F),
		helpstring("ComponentRegistrar Class")
	] 
#line 33 "d:\\work\\v1.18\\additional\\sbrf\\autosubscriptions\\activex component for sbrf\\source code dll\\sbrf\\compreg.h"
	coclass CCompReg {
		interface IComponentRegistrar;
	};

	[
		version(1.0),
		uuid(2C9823BE-15A3-4867-9852-8E4670F4C325),
		helpstring("Server Class")
	] 
#line 38 "d:\\work\\111\\acitvex\\server.h"
	coclass CServer {
		interface IServer;
	};

}

