CREATE TABLE "WAR_PEN"."AG_RS" ("AGREEMENT_MODE" NUMBER(9) NOT NULL, 
    "AGREEMENT_NUMBER" VARCHAR2(16 byte), "AGREEMENT_DATE" DATE 
    NOT NULL, "OWNED_BRANCH" NUMBER(9), "START_SERVICE" DATE NOT 
    NULL, "END_SERVICE" DATE, "CLIENT_ID" VARCHAR2(32 byte), 
    "CLIENT_TOKEN" VARCHAR2(64 byte), "CLIENT_GENDER" VARCHAR2(16
    byte), "CLIENT_BIRTHDATE" DATE, "CLIENT_CITIZEN" VARCHAR2(70 
    byte), "IC_TYPE" VARCHAR2(32 byte), "IC_TYPENAME" 
    VARCHAR2(128 byte), "IC_SERIES" VARCHAR2(16 byte), 
    "IC_NUMBER" VARCHAR2(16 byte), "IC_DATE_OF_ISSUE" DATE, 
    "IC_AUTHORITY" VARCHAR2(128 byte), "STATE" NUMBER(9) NOT NULL,
    "LAST_DATE" DATE, "NEXT_DATE" DATE NOT NULL, 
    "OUTSTANDING_DEBT" NUMBER(18, 2), "SERVICE_RATE" NUMBER(18, 
    2), "RESTORE_ACCESS" NUMBER(18, 2), "RESTORE_KEY" NUMBER(18, 
    2), "CLIENT_LOGIN" VARCHAR2(20 byte), "OFFICE" NUMBER(9), 
    "DEPO_NO_1" VARCHAR2(20 byte), "DEPO_NO_2" VARCHAR2(20 byte),
    "SURNAME" VARCHAR2(60 byte), "FIRSTNAME" VARCHAR2(30 byte), 
    "SECONDNAME" VARCHAR2(30 byte))  