<%@ page contentType="text/html;charset=windows-1251" language="java" %>
<%@ taglib prefix="html" uri="http://jakarta.apache.org/struts/tags-html" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="phiz" uri="http://rssl.com/tags" %>
<%@ taglib prefix="tiles" uri="http://jakarta.apache.org/struts/tags-tiles" %>
<%@ taglib uri="http://jakarta.apache.org/struts/tags-bean" prefix="bean" %>

<html:form styleId="viewInvoiceFormId" action="/basket/invoice/view" onsubmit="return setEmptyAction();" show="true">
    <c:set var="form" value="${phiz:currentForm(pageContext)}"/>
    <c:set var="invoice" value="${form.invoice}"/>
    <c:set var="subscriptionName" value="${form.subscriptionName}"/>
    <c:set var="bankName" value="${form.bankName}"/>
    <c:set var="bankAccount" value="${form.bankAccount}"/>
    <c:set var="availableOperations" value="${form.operationAvailable}"/>
    <c:set var="globalImagePath" value="${globalUrl}/images"/>
    <c:set var="commonImagePath" value="${globalUrl}/commonSkin/images"/>
    <c:set var="actionUrl" value="${phiz:calculateActionURL(pageContext, '/private/async/basket/invoice/process.do')}"/>
    <c:set var="paymentsUrl" value="${phiz:calculateActionURL(pageContext, '/private/payments.do')}"/>

    <html:hidden property="id" styleId="invoice_${invoice.id}"/>

    <div class="invoiceView">

        <div class="top">
            <div class="serviceTitle word-wrap">
                <c:out value="${invoice.nameService}"/>
            </div>
            <div class="serviceProviderTitle">
                <c:out value="${invoice.recName}"/>
            </div>
        </div>

        <c:if test="${!form.confirmSubscription}">
        <tiles:insert definition="warningBlock" flush="false">
            <tiles:put name="regionSelector" value="autoGeneratedMessage${invoice.id}"/>
            <tiles:put name="isDisplayed" value="true"/>
        <tiles:put name="data">
            <bean:message key="invoice.generated.view.message" bundle="basketBundle"/>
        </tiles:put>
        </tiles:insert>
        </c:if>

            <%-- Сообщения --%>
        <tiles:insert definition="warningBlock" flush="false">
            <tiles:put name="regionSelector" value="editEntityWarnings${invoice.id}"/>
            <tiles:put name="isDisplayed" value="${isEditable && needUngroupSubscriptions}"/>
        </tiles:insert>

            <%-- Ошибки --%>
        <tiles:insert definition="errorBlock" flush="false">
            <tiles:put name="regionSelector" value="editEntityErrors${invoice.id}"/>
            <tiles:put name="isDisplayed" value="false"/>
        </tiles:insert>

        <div id="invoicePaymentFormDiv${invoice.id}">
            <div class="body">
                <tiles:insert definition="formRow" flush="false">
                    <tiles:put name="title" value="Счет выставлен по услуге:"/>
                    <tiles:put name="data">
                    <span class="invoiceSubscriptionTitle">
                        <c:out value="${subscriptionName}"/>
                    </span>
                    </tiles:put>
                </tiles:insert>

                <h2 class="additionalInfoHeader fontForH2">Получатель</h2>

                <tiles:insert definition="formRow" flush="false">
                    <tiles:put name="title" value="Наименование:"/>
                    <tiles:put name="data">
                        <c:out value="${invoice.recName}"/>
                    </tiles:put>
                </tiles:insert>
                <tiles:insert definition="formRow" flush="false">
                    <tiles:put name="title" value="ИНН:"/>
                    <tiles:put name="data">
                        <c:out value="${invoice.recInn}"/>
                    </tiles:put>
                </tiles:insert>
                <tiles:insert definition="formRow" flush="false">
                    <tiles:put name="title" value="Счет:"/>
                    <tiles:put name="data">
                        <c:out value="${invoice.recAccount}"/>
                    </tiles:put>
                </tiles:insert>

                <h2 class="additionalInfoHeader fontForH2">Банк получателя</h2>

                <tiles:insert definition="formRow" flush="false">
                    <tiles:put name="title" value="Наименование:"/>
                    <tiles:put name="data">
                        <c:out value="${bankName}"/>
                    </tiles:put>
                </tiles:insert>
                <tiles:insert definition="formRow" flush="false">
                    <tiles:put name="title" value="БИК:"/>
                    <tiles:put name="data">
                        <c:out value="${invoice.recBic}"/>
                    </tiles:put>
                </tiles:insert>
                <c:if test="${not empty invoice.recCorAccount || not empty bankAccount}">
                    <tiles:insert definition="formRow" flush="false">
                        <tiles:put name="title" value="Корсчет:"/>
                        <tiles:put name="data">
                            <c:choose>
                                <c:when test="${not empty invoice.recCorAccount}">
                                    <c:out value="${invoice.recCorAccount}"/>
                                </c:when>
                                <c:otherwise>
                                    <c:out value="${bankAccount}"/>
                                </c:otherwise>
                            </c:choose>
                        </tiles:put>
                    </tiles:insert>
                </c:if>

                <h2 class="additionalInfoHeader fontForH2">Детали платежа</h2>

                <c:forEach var="field" items="${invoice.requisitesAsList}">
                    <c:choose>
                        <c:when test="${not field.mainSum && field.visible}">
                            <tiles:insert definition="formRow" flush="false">
                                <tiles:put name="title" value="${field.name}"/>
                                <tiles:put name="data">
                                    <c:out value="${field.value}"/>
                                </tiles:put>
                            </tiles:insert>
                        </c:when>
                        <c:when test="${field.mainSum}">
                            <c:set var="mainSum" value="${field}"/>
                        </c:when>
                    </c:choose>
                </c:forEach>

            </div>

            <div class="bottom">
                <tiles:insert definition="formRow" flush="false">
                    <tiles:put name="title" value="Счет списания:"/>
                    <tiles:put name="data">
                        <c:set var="cardNumber" value="${invoice.cardNumber}"/>
                        <c:set var="cardLink" value="${phiz:getCardLink(cardNumber)}"/>
                        <c:set var="card" value="${cardLink.value}"/>
                        <c:out value="${phiz:getCutCardNumber(cardNumber)}"/>&nbsp;
                        [<c:out value="${phiz:getCardUserName(cardLink)}"/>]&nbsp;
                        <c:if test="${not empty card.availableLimit}">
                            <c:out value="${phiz:formatAmount(card.availableLimit)}"/>
                        </c:if>
                    </tiles:put>
                </tiles:insert>

                <tiles:insert definition="formRow" flush="false">
                    <tiles:put name="title">
                        <span class="mainSumRow">Сумма</span>
                    </tiles:put>
                    <tiles:put name="data">
                        <div class="fullSumRow">
                        <span class="mainSumRow">
                            <bean:write name="mainSum" property="value" format="0.00"/>
                        </span>
                            <span class="currencyRow">руб.</span>
                        </div>
                    </tiles:put>
                </tiles:insert>

                <c:if test="${not empty invoice.commission}">
                    <tiles:insert definition="formRow" flush="false">
                        <tiles:put name="title">
                            <span class="commissionTitle">Комиссия</span>
                        </tiles:put>
                        <tiles:put name="data">
                        <span class="commissionValue">
                            <bean:write name="invoice" property="commission" format="0.00"/>
                        </span>
                        </tiles:put>
                    </tiles:insert>
                </c:if>
            </div>
        </div>

</html:form>