-- tbl ACCESSSCHEMES
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE S_ACCESSSCHEMES'; END;
go
-- tbl ACCOUNT_LINKS
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE S_ACCOUNT_LINKS'; END;
go

  ALTER TABLE ACCOUNT_LINKS MODIFY(EXTERNAL_ID VARCHAR2(26 BYTE))
go
  ALTER TABLE ACCOUNT_LINKS MODIFY(ACCOUNT_NUMBER VARCHAR2(25 BYTE))
go
  ALTER TABLE ACCOUNT_LINKS ADD (IS_CHANGED  CHAR(1 BYTE) DEFAULT 0 NOT NULL )
go

-- tbl ADDITIONAL_CLIENTS_IDS
  CREATE SEQUENCE S_ADDITIONAL_CLIENTS_IDS
go
  CREATE TABLE ADDITIONAL_CLIENTS_IDS (
         ID        INTEGER           NOT NULL,
         CLIENT_ID VARCHAR2(32 BYTE) NOT NULL,
         PARENT_ID INTEGER,

         CONSTRAINT PK_ADDITIONAL_CLIENTS_IDS PRIMARY KEY (ID)
  )
go

-- tbl ADDRESS
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE S_ADDRESS'; END;
go

-- tbl AUTHENTICATION_MODES
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE S_AUTHENTICATION_MODES'; END;
go

-- tbl CARD_LINKS
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE S_CARD_LINKS'; END;
go
  ALTER TABLE CARD_LINKS MODIFY(EXTERNAL_ID VARCHAR2(26 BYTE))
go

-- tbl CELLTYPES_TERMS_OF_LEASE
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE S_CELLTYPES_TERMS_OF_LEASE'; END;
go
  CREATE UNIQUE INDEX AK_KEY_1_CELLTYPE ON CELLTYPES_TERMS_OF_LEASE (CELLTYPE_ID, TERM_OF_LEASE_ID)
go
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CELLTYPES_TERMS_OF_LEASE DROP PRIMARY KEY CASCADE'; END;
go
  ALTER TABLE CELLTYPES_TERMS_OF_LEASE DROP COLUMN ID
go
-- tbl CHARGEOFFLOG
  CREATE SEQUENCE S_CHARGEOFFLOG
go
  CREATE TABLE CHARGEOFFLOG  (
         ID              INTEGER            NOT NULL,
         LOGIN_ID        INTEGER            NOT NULL,
         OPERATION_DATE  TIMESTAMP(6)  NOT NULL,
         TYPE            VARCHAR2(32 BYTE)  NOT NULL,
         AMOUNT          NUMBER(15,4),
         ACCOUNT         VARCHAR2(30 BYTE),
         PERIOD_FROM     TIMESTAMP(6),
         STATE           VARCHAR2(32 BYTE)  NOT NULL,
         CURRENCY        CHAR(3 BYTE),
         PERIOD_UNTIL    TIMESTAMP(6),
         ATTEMPT         INTEGER,
                   
         CONSTRAINT PK_CHARGEOFFLOG PRIMARY KEY (ID)
  )
go

-- tbl CODLOG
  ALTER TABLE CODLOG ADD (LOGIN_ID INTEGER)
go
    
-- tbl CURRENCY_OPERATION_TYPES
  ALTER TABLE CURRENCY_OPERATION_TYPES MODIFY(PRIM VARCHAR2(1024 BYTE))
go

-- tbl DEPOSITDESCRIPTIONS
  ALTER TABLE DEPOSITDESCRIPTIONS ADD (DEPARTMENT_ID  INTEGER NOT NULL)
go
  BEGIN EXECUTE IMMEDIATE 'DROP INDEX DEPOSITDESCRIPTIONS_UK_KEY'; END;
go
  CREATE UNIQUE INDEX DEPOSITDESCRIPTIONS_UK_KEY ON DEPOSITDESCRIPTIONS (NAME ASC, DEPARTMENT_ID ASC)
go

-- tbl DEPOSITGLOBALS
  ALTER TABLE DEPOSITGLOBALS ADD (ADMIN_LIST_TRANSFORMATION CLOB )
go
  ALTER TABLE DEPOSITGLOBALS ADD (ADMIN_EDIT_TRANSFORMATION CLOB )
go
  ALTER TABLE DEPOSITGLOBALS ADD (DEFAULT_DETAILS_TRANSFORMATION CLOB )
go

-- tbl DOCUMENTS
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE S_DOCUMENTS'; END;
go
  ALTER TABLE DOCUMENTS ADD (DOC_TIME_UP_DATE  TIMESTAMP(6))
go
  ALTER TABLE DOCUMENTS ADD (DOC_IDENTIFY  VARCHAR2(1 BYTE))
go
  UPDATE DOCUMENTS SET DOC_IDENTIFY = 1 WHERE DOC_TYPE = 'REGULAR_PASSPORT_RF'
go
  UPDATE DOCUMENTS SET DOC_IDENTIFY = 0 WHERE DOC_TYPE != 'REGULAR_PASSPORT_RF'
go

-- tbl EMPLOYEES
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE EMPLOYEES DROP CONSTRAINT FK_EMPLOYEE_TO_DEPARTMENTS'; END;
go

-- tbl ERRORMESSAGES
  ALTER TABLE ERRORMESSAGES MODIFY(MESSAGE  NULL)
go

-- tbl EXTERNAL_SYSTEMS
  CREATE SEQUENCE S_EXTERNAL_SYSTEMS
go
  CREATE TABLE EXTERNAL_SYSTEMS  (
         ID              INTEGER            NOT NULL,
         SYSTEM_UID      VARCHAR2(32 BYTE),
         NAME            VARCHAR2(32 BYTE),
         URL             VARCHAR2(128 BYTE),
         NUMBER_goROD    VARCHAR2(32 BYTE),
         PASSWORD_goROD  VARCHAR2(32 BYTE),

         CONSTRAINT PK_EXTERNAL_SYSTEMS PRIMARY KEY (ID)
  )
go

-- tbl EXTERNAL_SYSTEMS_LINKS
  CREATE SEQUENCE S_EXTERNAL_SYSTEMS_LINKS
go
  CREATE TABLE EXTERNAL_SYSTEMS_LINKS (
         ID                  INTEGER  NOT NULL,
         EXTERNAL_SYSTEM_ID  INTEGER,
         OFFICE_ID           VARCHAR2(32 BYTE),
                 
         CONSTRAINT PK_EXTERNAL_SYSTEMS_LINKS PRIMARY KEY (ID)
  )
go
  CREATE UNIQUE INDEX EXTERNAL_SYSTEMS_LINKS_UK ON EXTERNAL_SYSTEMS_LINKS (OFFICE_ID ASC)
go
  ALTER TABLE EXTERNAL_SYSTEMS_LINKS
              ADD CONSTRAINT FK_EXTERNAL_FK_TO_EXT_EXTERNAL FOREIGN KEY (EXTERNAL_SYSTEM_ID)
                  REFERENCES EXTERNAL_SYSTEMS (ID)
go
   
-- tbl FILTER_PARAMETERS
  CREATE SEQUENCE S_FILTER_PARAMETERS
go
  CREATE TABLE FILTER_PARAMETERS  (
         ID         INTEGER NOT NULL,
         SESSION_ID VARCHAR2(128 BYTE),
         URL        VARCHAR2(256 BYTE),
                  
         CONSTRAINT PK_FILTER_PARAMETERS PRIMARY KEY (ID)
  )
go

-- tbl FILTER_PARAMETERS_FIELDS
  CREATE SEQUENCE S_FILTER_PARAMETERS_FIELDS
go
  CREATE TABLE FILTER_PARAMETERS_FIELDS  (
         ID         INTEGER NOT NULL,
         FILTER_ID  INTEGER,
         PARAMETER  VARCHAR2(32 BYTE),
         VALUE      VARCHAR2(32 BYTE),

         CONSTRAINT PK_FILTER_PARAMETERS_FIELDS PRIMARY KEY (ID)
  )
go
  ALTER TABLE FILTER_PARAMETERS_FIELDS
        ADD CONSTRAINT FK_FILTER_P_FK_FIELDS_FILTER_P FOREIGN KEY (FILTER_ID)
            REFERENCES FILTER_PARAMETERS (ID) ON DELETE CASCADE
go

-- tbl GUID_TO_DOCUMENTID
  CREATE SEQUENCE S_GUID_TO_DOCUMENTID
go
  CREATE TABLE GUID_TO_DOCUMENTID (
         ID           INTEGER            NOT NULL,
         GUID         VARCHAR2(64 BYTE)  NOT NULL,
         DOCUMENT_ID  INTEGER            NOT NULL,

         CONSTRAINT PK_GUID_TO_DOCUMENTID PRIMARY KEY (ID)
  )
go

-- tbl LOGINS
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE S_LOGINS'; END;
go

-- tbl MAIL
  BEGIN EXECUTE IMMEDIATE 'DROP INDEX MAIL_INDEX_NUM'; END;
go
  CREATE UNIQUE INDEX MAIL_INDEX_NUM ON MAIL (NUM ASC, DIRECTION ASC, SENDER_ID ASC)
go

-- tbl PAYMENTS_SYSTEM_LINKS
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE S_PAYMENTS_SYSTEM_LINKS'; END;
go

-- tbl PSEUDONYMS
  CREATE SEQUENCE S_PSEUDONYMS
go
  CREATE TABLE PSEUDONYMS  (
         ID         INTEGER           NOT NULL,
         LOGIN_ID   INTEGER           NOT NULL,
         KIND       CHAR(1 BYTE)      NOT NULL,
         PNAME      VARCHAR2(20 BYTE) NOT NULL,
         VALUE      VARCHAR2(20 BYTE) NOT NULL,
         FLAG       CHAR(1 BYTE)      NOT NULL,

         CONSTRAINT PK_PSEUDONYMS PRIMARY KEY (ID)
  )
go
  ALTER TABLE PSEUDONYMS
        ADD CONSTRAINT FK_PSEUDONY_REFERENCE_LOGINS FOREIGN KEY (LOGIN_ID)
            REFERENCES LOGINS (ID)
go

-- tbl SCHEMEOWNS
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE S_SCHEMEOWNS'; END;
go

-- tbl SESSION_PARAMETERS
  CREATE SEQUENCE S_SESSION_PARAMETERS
go
  CREATE TABLE SESSION_PARAMETERS  (
         ID                INTEGER  NOT NULL,
         RANDOM_RECORD_ID  VARCHAR2(12 BYTE),
         URL               VARCHAR2(256 BYTE),
         PARAMETERS        CLOB,

         CONSTRAINT PK_SESSION_PARAMETERS PRIMARY KEY (ID)
  )
go

-- tbl SKINS
  CREATE SEQUENCE  S_SKINS
go
  CREATE TABLE SKINS  (
         ID           INTEGER           NOT NULL,
         NAME         VARCHAR2(32 BYTE)  NOT NULL,
         URL          VARCHAR2(100 BYTE) NOT NULL,
         SYSTEM_NAME  VARCHAR2(32 BYTE),
         CLIENT       CHAR(1 BYTE),
         ADMIN        CHAR(1 BYTE),

         CONSTRAINT PK_SKINS PRIMARY KEY (ID)
  )
go

-- tbl SMSPASSWORDS
  DELETE FROM SMSPASSWORDS
go
  ALTER TABLE SMSPASSWORDS ADD (ENTITY_TYPE VARCHAR2(128 BYTE) NOT NULL)
go
  ALTER TABLE SMSPASSWORDS ADD (ENTITY_ID   INTEGER            NOT NULL)
go

-- tbl SUBSCRIPTION_PARAMETERS
  ALTER TABLE SUBSCRIPTION_PARAMETERS MODIFY(VALUE VARCHAR2(1024 BYTE))
go

-- tbl SUBSCRIPTION_TEMPLATES
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE SUBSCRIPTION_TEMPLATES DROP CONSTRAINT FK_SUBTEM_TO_SUBS'; END;
go
  ALTER TABLE SUBSCRIPTION_TEMPLATES
        ADD CONSTRAINT FK_SUBTEM_TO_SUBS FOREIGN KEY (SUBSCRIPTION_ID)
            REFERENCES SUBSCRIPTIONS (ID) ON DELETE CASCADE
go

-- tbl TEMPLATES_DOCS_CONTRACT
  ALTER TABLE TEMPLATES_DOCS_CONTRACT ADD (FILE_NAME  VARCHAR2(128 BYTE))
go
  ALTER TABLE TEMPLATES_DOCS_CONTRACT ADD (FILE_TYPE  VARCHAR2(128 BYTE))
go

-- tbl CLAIM_EXTENDED_FIELDS
  ALTER TABLE CLAIM_EXTENDED_FIELDS DROP CONSTRAINT FK_CLAIM_TO_EX_FIELDS_CLAIMS
go
  DROP INDEX CLAIM_EXTENDED_FIELDS_CLAIM_ID
go
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE S_CLAIM_EXTENDED_FIELDS'; END;
go
  DROP TABLE CLAIM_EXTENDED_FIELDS
go

-- tbl CLAIMS
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS DROP CONSTRAINT FK_CLAIMS_TO_LOGINS'; END;
go
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS DROP CONSTRAINT FK_CLAIM_TO_SIGNATURE'; END;
go
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE CLAIMS DROP CONSTRAINT FK_CLAIMS_FK_DEPART_DEPARTME'; END;
go
  DROP INDEX CLAIMS_INDEX_OWNER
go
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE S_CLAIMS'; END;
go
  DROP TABLE CLAIMS
go

-- tbls BANKS, RUSBANKS, CURBANKS
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BANKS DROP CONSTRAINT PK_BANKS'; END;
go
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BANKS DROP CONSTRAINT AK_UK_BANKS_BIC'; END;
go
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE BANKS DROP CONSTRAINT AK_UK_BANKS_SWIFT'; END;
go
  ALTER TABLE BANKS DROP (KIND)
go
  ALTER TABLE BANKS DROP (SWIFT)
go
  ALTER TABLE BANKS ADD  (OUR CHAR(1 BYTE))
go
  ALTER TABLE BANKS RENAME TO RUSBANKS
go 
  ALTER TABLE RUSBANKS ADD CONSTRAINT PK_RUSBANKS PRIMARY KEY (ID)
go
  ALTER TABLE RUSBANKS ADD CONSTRAINT AK_UK_BANKS_BIC UNIQUE (BIC)
go
  CREATE TABLE CURBANKS  (
         ID                   VARCHAR2(64 BYTE)    NOT NULL,
         NAME                 VARCHAR2(256 BYTE)   NOT NULL,
         SWIFT                VARCHAR2(26 BYTE),
         PLACE                VARCHAR2(50 BYTE),
         CORR_ACCOUNT         VARCHAR2(26 BYTE),
         SHORT_NAME           VARCHAR2(256 BYTE),
         COUNTRY              VARCHAR2(4 BYTE),
         ADDRESS              VARCHAR2(256 BYTE),

         CONSTRAINT PK_CURBANKS PRIMARY KEY (ID),
         CONSTRAINT AK_UK_BANKS_SWIFT UNIQUE (SWIFT)
  )
go

-- tbl DEPARTMENTS
  ALTER TABLE DEPARTMENTS ADD (TEMP_OFFICE  VARCHAR2(4 BYTE))
go 
  DROP INDEX DEPARTMENTS_INDEX_OFFICE
go    
  ALTER TABLE DEPARTMENTS DROP CONSTRAINT FK_DEPARTME_FK_DEPART_OFFICES
go
  ALTER TABLE DEPARTMENTS ADD (PARENT_DEPARTMENT  INTEGER)
go
  ALTER TABLE DEPARTMENTS ADD (POSTINDEX  VARCHAR2(6 BYTE))
go
  ALTER TABLE DEPARTMENTS ADD (BIC  VARCHAR2(26 BYTE))
go
  ALTER TABLE DEPARTMENTS ADD (OSB  VARCHAR2(4 BYTE))
go
  ALTER TABLE DEPARTMENTS ADD (OFFICE  VARCHAR2(7 BYTE))
go
  ALTER TABLE DEPARTMENTS MODIFY(OFFICE_ID  NULL)
go
  ALTER TABLE DEPARTMENTS ADD (SBIDNT  VARCHAR2(4 BYTE))
go
  ALTER TABLE DEPARTMENTS ADD (SERVICE CHAR(1 BYTE) DEFAULT 0)
go
  ALTER TABLE DEPARTMENTS ADD (TIME_ZONE  INTEGER DEFAULT 0)
go
  ALTER TABLE DEPARTMENTS ADD (USE_PARENT_CONNECTION_CHARGE  CHAR(1 BYTE) DEFAULT 0 NOT NULL)
go
  ALTER TABLE DEPARTMENTS ADD (USE_PARENT_MONTHLY_CHARGE     CHAR(1 BYTE) DEFAULT 0 NOT NULL)
go
  ALTER TABLE DEPARTMENTS ADD (USE_PARENT_TIME_SETTINGS      CHAR(1 BYTE) DEFAULT 0 NOT NULL)
go
  ALTER TABLE DEPARTMENTS
        ADD CONSTRAINT FK_DEPARTME_TO_DEPARTME FOREIGN KEY (PARENT_DEPARTMENT)
            REFERENCES DEPARTMENTS (ID)
go
 --2 сотрудника оказались без департамента, поэтому устанавливаю ему department_id равное 24 (Тестовое ОСБ2) 
 UPDATE EMPLOYEES SET DEPARTMENT_ID = '24' WHERE (ID = 3088) OR (ID = 3089)
go


-- tbl OFFICES
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE RECEIVERS DROP CONSTRAINT FK_RECEIVER_TO_OFFICES'; END;
go
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE OFFICE_CELLTYPES DROP CONSTRAINT FK_OFFICE_C_FK_OFFICE_OFFICES'; END;
go
  DROP INDEX OFFICES_INDEX_CODE
go

-- tbl OFFICE_CELLTYPES
  ALTER TABLE OFFICE_CELLTYPES DROP COLUMN OFFICE_ID
go
  ALTER TABLE OFFICE_CELLTYPES ADD (DEPARTMENT_ID INTEGER NOT NULL)
go
  ALTER TABLE OFFICE_CELLTYPES
        ADD CONSTRAINT FK_OFFICE_C_FK_OFFICE_DEPARTME FOREIGN KEY (DEPARTMENT_ID)
            REFERENCES DEPARTMENTS (ID)
go

-- tbl RECEIVERS
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE S_RECEIVERS'; END;
go
  ALTER TABLE RECEIVERS DROP COLUMN OFFICE_KEY
go
  ALTER TABLE RECEIVERS MODIFY(STATUS VARCHAR2(12))
go
  UPDATE RECEIVERS SET STATUS = 'ACTIVE'
go
  ALTER TABLE RECEIVERS MODIFY(STATUS VARCHAR2(12) NOT NULL)
go

-- tbl ALLOWED_DEPARTMENT
  CREATE TABLE ALLOWED_DEPARTMENT  (
         DEPARTMENT_ID  INTEGER  NOT NULL,
         LOGIN_ID       INTEGER  NOT NULL,
 
         CONSTRAINT PK_ALLOWED_DEPARTMENT PRIMARY KEY (DEPARTMENT_ID, LOGIN_ID)
  )
go
  ALTER TABLE ALLOWED_DEPARTMENT
        ADD CONSTRAINT FK_ALLOWED_DEP_TO_DEPARTME FOREIGN KEY (DEPARTMENT_ID)
            REFERENCES DEPARTMENTS (ID) ON DELETE CASCADE
go
  ALTER TABLE ALLOWED_DEPARTMENT
        ADD CONSTRAINT FK_ALLOWED_DEP_TO_LOGINS FOREIGN KEY (LOGIN_ID)
            REFERENCES LOGINS (ID)
go
         
-- tbl FORM_PACKAGES
  CREATE TABLE FORM_PACKAGES  (
         FORM_ID     INTEGER  NOT NULL,
         PACKAGE_ID  INTEGER  NOT NULL,
         LIST_INDEX  INTEGER  NOT NULL,

         CONSTRAINT PK_FORM_PACKAGES PRIMARY KEY (FORM_ID, PACKAGE_ID)
  )
go
  ALTER TABLE FORM_PACKAGES
        ADD CONSTRAINT FK_FORM_PACKAGES_TO_FORM FOREIGN KEY (FORM_ID)
            REFERENCES PAYMENTFORMS (ID)
go
  ALTER TABLE FORM_PACKAGES
        ADD CONSTRAINT FK_FORM_PACKAGES_TO_PACKAGE FOREIGN KEY (PACKAGE_ID)
            REFERENCES TEMPLATESPACKAGE (ID)
go


-- tbl FORM_TEMPLATES
  CREATE TABLE FORM_TEMPLATES  (
         FORM_ID              INTEGER    NOT NULL,
         TEMPLATE_ID          INTEGER    NOT NULL,
         LIST_INDEX           INTEGER    NOT NULL,
 
        CONSTRAINT PK_FORM_TEMPLATES PRIMARY KEY (FORM_ID, TEMPLATE_ID)
  )
go

  ALTER TABLE FORM_TEMPLATES
        ADD CONSTRAINT FK_FORM_TEMPLATES_TO_FORM FOREIGN KEY (FORM_ID)
            REFERENCES PAYMENTFORMS (ID)
go

  ALTER TABLE FORM_TEMPLATES
        ADD CONSTRAINT FK_FORM_TEMPLATES_TO_TEMPLATE FOREIGN KEY (TEMPLATE_ID)
            REFERENCES TEMPLATES_DOCS_CONTRACT (ID)
go 

-- tbl REPRESENTATIVES
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE REPRESENTATIVES DROP CONSTRAINT  FK_REPR_TO_DEPARTMENTS'; END;
go
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE REPRESENTATIVES DROP CONSTRAINT PK_REPRESENTATIVES'; END;
go
  DROP  TABLE REPRESENTATIVES
go
    
-- tbl USERS
  BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE S_USERS'; END; 
go
  ALTER TABLE USERS MODIFY(CLIENT_ID VARCHAR2(38 BYTE))
go
  ALTER TABLE USERS MODIFY(MESSAGE_SERVICE VARCHAR2(20 BYTE))
go
  ALTER TABLE USERS ADD  (DISPLAY_CLIENT_ID  VARCHAR2(32 BYTE))
go
  ALTER TABLE USERS DROP ( REPRESENTATIVE_ID )
go
  UPDATE USERS SET DISPLAY_CLIENT_ID = CLIENT_ID
go

-- tbl PAYMENTS
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PAYMENTS DROP CONSTRAINT FK_PAYMENTS_FK_DEPART_DEPARTME'; END; 
go
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PAYMENTS DROP CONSTRAINT FK_PAYMENT_TO_SIGNATURE'; END;
go
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PAYMENTS DROP CONSTRAINT PAYMENT_TO_FORM'; END;
go
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PAYMENTS DROP CONSTRAINT PAYMENT_TO_LOGIN'; END;
go
  RENAME S_PAYMENTS TO S_BUSINESS_DOCUMENTS
go
  DROP INDEX PAYMENTS_INDEX_FORM_ID
go
  DROP INDEX PAYMENTS_INDEX_LOGIN_ID
go
  DROP INDEX PAYMENTS_INDEX_OPERATION_DATE
go
  DROP INDEX PAYMENTS_INDEX_DEPARTMENT_ID
go
  ALTER TABLE PAYMENTS RENAME COLUMN DOC_DATE TO DOCUMENT_DATE
go
  ALTER TABLE PAYMENTS RENAME COLUMN BIRTH_DATE TO CREATION_DATE
go
  ALTER TABLE PAYMENTS ADD (STATE_CODE VARCHAR2(20 BYTE))
go
  ALTER TABLE PAYMENTS ADD (EXECUTION_DATE TIMESTAMP(6))
go 
  ALTER TABLE PAYMENTS ADD (CREATION_TYPE CHAR(1 BYTE) DEFAULT 1 NOT NULL) 
go
  ALTER TABLE PAYMENTS ADD (ARCHIVE CHAR(1 BYTE) DEFAULT 0)
go
  ALTER TABLE PAYMENTS ADD (STATE_MACHINE_NAME   VARCHAR2(50 BYTE))
go
  ALTER TABLE PAYMENTS ADD (REFUSING_REASON      VARCHAR2(256 BYTE))
go
  ALTER TABLE PAYMENTS ADD (EXTERNAL_OWNER_ID    VARCHAR2(38 BYTE))
go
  UPDATE PAYMENTS SET KIND = 'R' WHERE (FORM_ID = '2') AND (KIND = 'C')
go
  UPDATE PAYMENTS SET KIND = 'E' WHERE (FORM_ID = '3') AND (KIND = 'K')
go
  UPDATE PAYMENTS SET KIND = 'O' WHERE (FORM_ID = '4') AND (KIND = 'A')
go
  UPDATE PAYMENTS SET KIND = 'R' WHERE (FORM_ID = '5') AND (KIND = 'C')
go
  UPDATE PAYMENTS SET KIND = 'P' WHERE (FORM_ID = '6') AND (KIND = 'J')
go
  UPDATE PAYMENTS SET KIND = 'H' WHERE (FORM_ID = '7') AND (KIND = 'R')    
go
  UPDATE PAYMENTS SET KIND = 'R' WHERE (FORM_ID = '8') AND (KIND = 'C')
go

-- tbl PAYMENT_EXTENDED_FIELDS
  DROP INDEX PAYMENT_EXTENDED_FIELDS_P_ID
go
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PAYMENT_EXTENDED_FIELDS DROP CONSTRAINT FK_EXT_FIELDS_TO_PAYMENTS'; END;
go
  ALTER TABLE PAYMENT_EXTENDED_FIELDS MODIFY (NAME VARCHAR2(64 BYTE))
go
  RENAME S_PAYMENT_EXTENDED_FIELDS TO S_DOCUMENT_EXTENDED_FIELDS
go
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PAYMENT_EXTENDED_FIELDS DROP CONSTRAINT PK_PAYMENT_EXTENDED_FIELDS'; END;
go
  ALTER TABLE PAYMENT_EXTENDED_FIELDS RENAME TO DOCUMENT_EXTENDED_FIELDS
go
  ALTER TABLE DOCUMENT_EXTENDED_FIELDS ADD CONSTRAINT PK_DOCUMENT_EXTENDED_FIELDS PRIMARY KEY (ID)
go
  CREATE INDEX DOCUMENT_EXTENDED_FIELDS_P_ID ON DOCUMENT_EXTENDED_FIELDS (PAYMENT_ID ASC)
go
  BEGIN EXECUTE IMMEDIATE 'ALTER TABLE PAYMENTS DROP CONSTRAINT PK_PAYMENTS'; END;
go
  ALTER TABLE PAYMENTS RENAME TO BUSINESS_DOCUMENTS
go
  ALTER TABLE BUSINESS_DOCUMENTS ADD CONSTRAINT PK_BUSINESS_DOCUMENTS PRIMARY KEY (ID)
go
  ALTER TABLE DOCUMENT_EXTENDED_FIELDS 
        ADD CONSTRAINT FK_EXT_FIELDS_TO_PAYMENTS FOREIGN KEY (PAYMENT_ID)
            REFERENCES BUSINESS_DOCUMENTS (ID)
go
  CREATE INDEX BUSINESS_DOCUMENTS_I_FORM_ID on BUSINESS_DOCUMENTS (FORM_ID ASC)
go
  CREATE INDEX BUSINESS_DOCUMENTS_I_LOGIN_ID on BUSINESS_DOCUMENTS (LOGIN_ID ASC)
go
  CREATE INDEX BUSINESS_DOCUMENTS_I_OPER_DATE on BUSINESS_DOCUMENTS (OPERATION_DATE ASC)
go
  CREATE INDEX BUSINESS_DOCUMENTS_I_DEP on BUSINESS_DOCUMENTS (DEPARTMENT_ID ASC)
go
  ALTER TABLE BUSINESS_DOCUMENTS
        ADD CONSTRAINT FK_BUSINESS_FK_DEPART_DEPARTME FOREIGN KEY (DEPARTMENT_ID)
            REFERENCES DEPARTMENTS (ID)
go
  ALTER TABLE BUSINESS_DOCUMENTS
        ADD CONSTRAINT FK_PAYMENT_TO_SIGNATURE FOREIGN KEY (SIGNATURE_ID)
            REFERENCES SIGNATURES (ID)
go
  ALTER TABLE BUSINESS_DOCUMENTS
        ADD CONSTRAINT PAYMENT_TO_FORM FOREIGN KEY (FORM_ID)
             REFERENCES PAYMENTFORMS (ID)
go
  ALTER TABLE BUSINESS_DOCUMENTS
        ADD CONSTRAINT PAYMENT_TO_LOGIN FOREIGN KEY (LOGIN_ID)
            REFERENCES LOGINS (ID)
go

