ALTER INDEX SUBSCRIPTION_PARAMETERS_SUB_ID RENAME TO REFERENCE_7_FK
go
ALTER INDEX CODLOG_COMLOG_INDEX RENAME TO COMLOG_INDEX_4
go
ALTER INDEX EMPLOYEES_INDEX_LOGIN RENAME TO EMPLOYEE_TO_LOGINS_FK
go
ALTER INDEX BUSINESS_DOCUMENTS_I_DEP RENAME TO FK_DEPARTMENTS_TO_PAYMENTS_FK
go
ALTER INDEX FNS_FIELDS_ORDERS RENAME TO ORDERS_2
go
ALTER INDEX CODLOG_INDEX_MESSAGE_DEMAND_ID RENAME TO INDEX_MESSAGE_DEMAND_ID
go
ALTER INDEX TEMPLATES_DOCS_CONTRACT_IND_DP RENAME TO TMM_TO_DEPARTMENT_FK
go
ALTER INDEX BUSINESS_DOCUMENTS_I_KINDSTATE RENAME TO I_KINDSTATE
go
ALTER INDEX SERVICE_PROVIDERS_IND_ACC_INN RENAME TO IND_ACC_INN
go
ALTER INDEX MAIL_INDEX_NUM RENAME TO INDEX_NUM
go
ALTER INDEX RECEIVERS_INDEX_LOGIN_ID RENAME TO RECEIVERS_TO_LOGINS_FK
go
ALTER INDEX INCOME_CONDITIONS_I_LIM_1 RENAME TO FK_CONDITION2_TO_LIMIT1_FK
go
ALTER INDEX CODLOG_SYS_DATE_INDEX RENAME TO SYS_DATE_INDEX
go
ALTER INDEX PAYMENTFORMS_INDEX_NAME RENAME TO INDEX_NAME_1
go
ALTER INDEX ACCOUNT_LINKS_I_NUMBER_LOGIN RENAME TO I_NUMBER_LOGIN
go
ALTER INDEX INDIVIDUAL_LIMITS_LOGIN_DATE RENAME TO LOGIN_DATE
go
ALTER INDEX CURRENCIES_INDEX_NUMERICCODE RENAME TO INDEX_NUMERICCODE
go
ALTER INDEX SERVICE_PROVIDERS_IDX_MB_CODE RENAME TO IDX_MB_CODE
go
ALTER INDEX TEMPLATESPACKAGE_DEPARTMENT_ID RENAME TO PACKAGE_TO_DEPARTMENT_FK
go
ALTER INDEX CREDIT_CARD_CONDITIONS_I_LIM_1 RENAME TO FK_CONDITION_TO_LIMIT_1_FK
go
ALTER INDEX SERVICES_KEY_UK RENAME TO KEY_UK
go
ALTER INDEX RESOURCEOWNS_TYPE_ID RENAME TO OWNS_TO_TYPES_FK
go
ALTER INDEX USERLOG_COMLOG_INDEX RENAME TO COMLOG_INDEX_2
go
ALTER INDEX CURRENCIES_INDEX_CODE RENAME TO INDEX_CODE_3
go
ALTER INDEX EMPLOYEES_INDEX_SUR_NAME RENAME TO INDEX_SUR_NAME
go
ALTER INDEX LIMITS_INDEX_START_DATE RENAME TO INDEX_START_DATE_1
go
ALTER INDEX CARDPASSWORDS_INDEX_CARD_ID RENAME TO PASSWORDS_TO_CARDS_FK
go
ALTER INDEX XSLT_IDX_XSLT_NAME RENAME TO IDX_XSLT_NAME
go
ALTER INDEX SECURITY_INDEX_INSIDE_CODE RENAME TO INDEX_INSIDE_CODE
go
ALTER INDEX USERS_INDEX_DEPARTMENT RENAME TO INDEX_DEPARTMENT_2
go
ALTER INDEX UGROUP_I_DEFAULT_SKIN_ID RENAME TO FK_DEFAULT_SKIN_ID_FK
go
ALTER INDEX DISTRIBUTIONS_DISTRIBUTION_KEY RENAME TO DISTRIBUTION_KEY
go
ALTER INDEX KBK_INDEX_CODE RENAME TO INDEX_CODE_5
go
ALTER INDEX UGROUP_I_SYSTEM_NAME RENAME TO I_SYSTEM_NAME
go
ALTER INDEX DOCUMENT_EXTENDED_FIELDS_P_ID RENAME TO EXT_FIELDS_TO_PAYMENTS_FK
go
ALTER INDEX SUBSCRIPTIONS_UK RENAME TO UK_3
go
ALTER INDEX PROFILE_LOGIN_ID_UNIQUE RENAME TO LOGIN_ID_UNIQUE
go
ALTER INDEX AUTO_PAYMENT_LINKS_I_LOGIN_ID RENAME TO I_LOGIN_ID
go
ALTER INDEX CLIENTSPACKAGESTEMPLATES_LOGIN RENAME TO PACKAGE_TO_LOGIN_FK
go
ALTER INDEX INCOME_CONDITIONS_I_LIM_2 RENAME TO FK_CONDITION2_TO_LIMIT2_FK
go
ALTER INDEX AUTO_PAYMENT_LINKS_UNIQ_EXT_ID RENAME TO UNIQ_EXT_ID
go
ALTER INDEX ORDERS_ORDERS RENAME TO ORDERS_3
go
ALTER INDEX BUSINESS_DOCUMENTS_I_EXTKIND RENAME TO I_EXTKIND
go
ALTER INDEX REGIONS_INDEX_CODE RENAME TO INDEX_CODE_2
go
ALTER INDEX COUNTERS_NAME_INDEX RENAME TO NAME_INDEX
go
ALTER INDEX STATEMENTS_I_CLAIM_ID RENAME TO FK_STATEMENT_TO_BUSINESS_DOCUM
go
ALTER INDEX SCHEDULE_EXPRESSION_UK RENAME TO EXPRESSION_UK
go
ALTER INDEX LOGIN_BLOCK_INDEX_LOGIN_ID RENAME TO FK_BLOCKS_TO_LOGIN_FK
go
ALTER INDEX PASSWORDCARDS_CARD_NUM_INDEX RENAME TO CARD_NUM_INDEX
go
ALTER INDEX RESOURCEOWNS_LOGIN_ID RENAME TO OWNS_TO_LOGINS_FK
go
ALTER INDEX DEPOSITDESCRIPTIONS_UK_KEY RENAME TO UK_KEY
go
ALTER INDEX EMPLOYEES_INDEX_DEPARTMENT RENAME TO INDEX_DEPARTMENT_1
go
ALTER INDEX SYSTEMLOG_LVL_DATE_INDEX RENAME TO LVL_DATE_INDEX
go
ALTER INDEX SYSTEMLOG_SRC_DATE_INDEX RENAME TO SRC_DATE_INDEX
go
ALTER INDEX RECEIVERS_INDEX_KIND RENAME TO INDEX_KIND
go
ALTER INDEX RECIPIENTS_INDEX_MAIL_ID RENAME TO RECIPIENTS_TO_MAIL_FK
go
ALTER INDEX BUSINESS_DOCUMENTS_I_FORM_ID RENAME TO PAYMENT_TO_FORM_FK
go
ALTER INDEX DOCUMENTS_DOC_NUMBER RENAME TO DOC_NUMBER
go
ALTER INDEX LOAN_LINKS_IND_NUMB_LOGIN_ID RENAME TO IND_NUMB_LOGIN_ID
go
CREATE  INDEX FK_CONDITION_TO_LOAN_PROD_FK ON LOAN_PRODUCT_CONDITIONS (
   PRODUCT_ID ASC
)
go
ALTER INDEX PINENVELOPES_USER_ID_UC RENAME TO USER_ID_UC
go
ALTER INDEX RESTRICTIONS_UK RENAME TO UK_2
go
ALTER INDEX CARD_LINKS_UNIQ_CARD_NUMBER RENAME TO UNIQ_CARD_NUMBER
go
ALTER INDEX ACCESSSCHEMES_INDEX_CATEGORY RENAME TO INDEX_CATEGORY
go
ALTER INDEX CODLOG_APP_DATE_INDEX RENAME TO APP_DATE_INDEX_2
go
ALTER INDEX FIELD_DESCRIPTIONS_R_IN RENAME TO R_IN
go
ALTER INDEX MESSAGE_TEMPLATES_CHANNEL_UK RENAME TO CHANNEL_UK
go
ALTER INDEX XMLPERSONREPRESENTATION_USERID RENAME TO USERID
go
ALTER INDEX BUSINESS_DOCUMENTS_I_LOGIN_ID RENAME TO PAYMENT_TO_LOGIN_FK
go
ALTER INDEX DOCUMENTS_DOC_INDEX RENAME TO DOC_INDEX
go
ALTER INDEX DEPPRODUCTRESTRICTIONS_PRODUCT RENAME TO DEPRESTR_TO_DEPOSITPROD_FK
go
ALTER INDEX SERVICE_PROVIDERS_INDEX_EXT_ID RENAME TO INDEX_EXT_ID
go
ALTER INDEX CODLOG_INDEX_START_DATE RENAME TO INDEX_START_DATE_2
go
ALTER INDEX CREDIT_CARD_CONDITIONS_I_PROD RENAME TO FK_CONDITION_TO_CRED_CARD_PROD
go
ALTER INDEX PAYMENTFORMS_INDEX_DESCRIPTION RENAME TO INDEX_DESCRIPTION_3
go
ALTER INDEX CONTACT_RECEIVERS_RECEIVER_ID RENAME TO RECEIVER_ID
go
ALTER INDEX DEPOSITDESCRIPTIONS_UK_P_ID RENAME TO UK_P_ID
go
ALTER INDEX CREDIT_CARD_CONDITIONS_I_LIM_2 RENAME TO FK_CONDITION_TO_LIMIT_2_FK
go
ALTER INDEX SERVICE_PROVIDERS_IDX_ALLOWP RENAME TO IDX_ALLOWP
go
ALTER INDEX PASSWORDCARDS_LOGIN_ID_INDEX RENAME TO CARDS_TO_LOGINS_FK
go
ALTER INDEX SYSTEMLOG_INDEX_LOGIN_ID RENAME TO INDEX_LOGIN_ID_1
go
ALTER INDEX SYSTEMLOG_APP_DATE_INDEX RENAME TO APP_DATE_INDEX_3
go
CREATE  INDEX FK_LOAN_PROD_DEP_TO_PROD_FK ON LOAN_PRODUCT_DEPARTMENT (
   PRODUCT_ID ASC
)
go
ALTER INDEX PASSWORDS_INDEX_LOGIN_ID RENAME TO PASSWORDS_LOGIN_FK
go
ALTER INDEX DEPO_ACCOUNT_LINKS_I_NUM_LOGIN RENAME TO I_NUM_LOGIN
go
ALTER INDEX USERS_INDEX_LOGIN RENAME TO USERS_LOGINS_FK
go
ALTER INDEX USERLOG_INDEX_SUCCESS_DESCR RENAME TO INDEX_SUCCESS_DESCR
go
ALTER INDEX USERS_COMLOG_INDEX RENAME TO COMLOG_INDEX_3
go
ALTER INDEX LOGINS_INDEX_USER_ID RENAME TO INDEX_USER_ID
go
ALTER INDEX SERVICE_PROVIDERS_IND_IMAGE_ID RENAME TO IND_IMAGE_ID_1
go
ALTER INDEX DOCUMENTS_DOC_SERIES RENAME TO DOC_SERIES
go
ALTER INDEX BUSINESS_DOCUMENTS_I_OPER_DATE RENAME TO I_OPER_DATE
go
ALTER INDEX PAYMENT_TEMPLATE_LINKS_EXTID RENAME TO EXTID
go
ALTER INDEX SCHEDULE_SCHEDULE_KEY RENAME TO SCHEDULE_KEY
go
ALTER INDEX BUSINESS_DOCUMENTS_IND_CR_DATE RENAME TO IND_CR_DATE
go
ALTER INDEX PAYMENTLISTS_INDEX_NAME RENAME TO INDEX_NAME_2
go
ALTER INDEX COMMISSIONVALS_IDX_CUR RENAME TO IDX_CUR
go
ALTER INDEX DEPARTMENTS_BILLING_ID_INDEX RENAME TO BILLING_ID_INDEX
go
ALTER INDEX SHOP_FIELDS_ORDERS RENAME TO ORDERS_1
go
ALTER INDEX USERSLIMIT_INDEX_DATE RENAME TO INDEX_DATE_7
go
ALTER INDEX SERVICEOPERATIONS_SERVICE_ID RENAME TO FK_SERVICEOPER_TO_SERVICES_FK
go
ALTER INDEX SYSTEMLOG_COMLOG_INDEX RENAME TO COMLOG_INDEX_5
go
CREATE  INDEX FK_LOAN_PROD_DEP_TO_DEP_FK ON LOAN_PRODUCT_DEPARTMENT (
   DEPARTMENT_ID ASC
)
go
ALTER INDEX RECEPTIONTIMES_INDEX_DEPFORM RENAME TO INDEX_DEPFORM
go
ALTER INDEX USERLOG_INDEX_LOGIN_ID RENAME TO INDEX_LOGIN_ID_2
go
ALTER INDEX INCOME_CONDITIONS_I_INCOME RENAME TO FK_CONDITION_TO_INCOME_LEVEL_F
go
ALTER INDEX USERS_SKIN_ID_INDEX RENAME TO FK_USERS_SKIN_ID_FK
go
ALTER INDEX PAYMENT_SERVICES_IND_IMAGE_ID RENAME TO IND_IMAGE_ID_2
go
ALTER INDEX USERLOG_INDEX_DESCRIPTION RENAME TO INDEX_DESCRIPTION_4
go
ALTER INDEX EMPLOYEES_COMLOG_INDEX RENAME TO COMLOG_INDEX_1
go
ALTER INDEX SYSTEMLOG_DATE_INDEX RENAME TO DATE_INDEX_1
go
ALTER INDEX ADAPTERS_INDEX_UUID RENAME TO INDEX_UUID
go
ALTER INDEX USERLOG_DATE_INDEX RENAME TO DATE_INDEX_2
go
ALTER INDEX DEPARTMENTS_INDEX_DEP_PARENT RENAME TO INDEX_DEP_PARENT
go
ALTER INDEX DOCUMENTS_DOC_TYPE RENAME TO DOC_TYPE
go
ALTER INDEX SCHEMEOWNS_UK RENAME TO UK_4
go
ALTER INDEX DOCUMENT_EXTENDED_FIELDS_I_PNV RENAME TO I_PNV
go
ALTER INDEX LOAN_PRODUCTS_I_LOAN_KIND_ID RENAME TO I_LOAN_KIND_ID
go
ALTER INDEX BILLINGS_INDEX_CODE RENAME TO INDEX_CODE_4
go
ALTER INDEX USERS_INDEX_CLIENT RENAME TO INDEX_CLIENT
go
ALTER INDEX PFRLINKS_I_LOGIN_ID RENAME TO FK_PFRLINKS_TO_LOGINS_FK
go
ALTER INDEX NEWS_INDEX_DATE RENAME TO INDEX_DATE_6
go
ALTER INDEX USERLOG_INDEX_FOR_REPORTS RENAME TO INDEX_FOR_REPORTS
go
ALTER INDEX SMSPASSWORDS_INDEX_LOGIN_ID RENAME TO FK_SMSPSW_TO_LOGINS_FK
go
ALTER INDEX PAYMENT_SERVICES_INDEX_CODE RENAME TO INDEX_CODE_1
go
ALTER INDEX REPORTS_INDEX_STATE_REPORTS RENAME TO INDEX_STATE_REPORTS
go
ALTER INDEX SERVICEOPERATIONS_OPERATION_ID RENAME TO FK_OPERSERVICE_TO_OPERATION_FK
go
CREATE  INDEX FK_DAOF_TO_RES_ADDRESS_FK ON DEPO_ACCOUNT_OWNER_FORM (
   RESIDENCE_ADDRESS ASC
)
go
CREATE  INDEX FK_ALLOWED_DEP_TO_LOGINS_FK ON ALLOWED_DEPARTMENT (
   LOGIN_ID ASC
)
go
CREATE  INDEX ELEMENT_TO_TEMPLATES_FK ON DOCUMENTS_PACKAGE (
   TEMPLATE_ID ASC
)
go
CREATE  INDEX REFERENCE_17_FK ON RECEPTIONTIMES (
   CALENDAR_ID ASC
)
go
CREATE  INDEX FK_DAOF_TO_M_ADDRESS_FK ON DEPO_ACCOUNT_OWNER_FORM (
   MAIL_ADDRESS ASC
)
go
CREATE  INDEX FK_RESTRICT_REFERENCE_SERVICES ON RESTRICTIONS (
   SERVICE_ID ASC
)
go
CREATE  INDEX FK_RESOURCES_TO_BUSINESS_DOCUM ON BUSINESS_DOCUMENTS_RES (
   BUSINESS_DOCUMENT_ID ASC
)
go
CREATE  INDEX "Reference_29_FK" ON SCHEMESSERVICES (
   SERVICE_ID ASC
)
go
CREATE  INDEX REFERENCE_19_FK ON USERSLIMIT (
   LOGIN_ID ASC
)
go
CREATE  INDEX FK_EXT_LINK_TO_RES_TYPE_FK ON RESOURCELINKS (
   TYPE_ID ASC
)
go
CREATE  INDEX REG_REF_FK ON PROFILE (
   REGION_ID ASC
)
go
CREATE  INDEX FK_PROV_REG_TO_PROV_FK ON SERVICE_PROVIDER_REGIONS (
   SERVICE_PROVIDER_ID ASC
)
go
CREATE  INDEX FK_S_PROVIDERS_TO_BILLINGS_FK ON SERVICE_PROVIDERS (
   BILLING_ID ASC
)
go
CREATE  INDEX COMMISSION_TO_VALS_FK ON COMMISSIONVALS (
   COMMISSION_ID ASC
)
go
CREATE  INDEX FK_CELLTYPE_FK_CELLTY_CELLTYPE ON CELLTYPES_TERMS_OF_LEASE (
   CELLTYPE_ID ASC
)
go
CREATE  INDEX FK_VAL_PARAM_TO_VALID_FK ON FIELD_VALIDATORS_PARAM (
   FIELD_ID ASC
)
go
CREATE  INDEX FK_DEPOLINKS_TO_LOGINS_FK ON DEPO_ACCOUNT_LINKS (
   LOGIN_ID ASC
)
go
CREATE  INDEX FK_RESTRICT_REFERENCE_OPERATIO ON RESTRICTIONS (
   OPERATION_ID ASC
)
go
CREATE  INDEX "DEMADS _REFERENCE_LOGINS_FK" ON CERT_DEMANDS (
   LOGIN_ID ASC
)
go
CREATE  INDEX FK_NODES_TO_NODE_ADAPTERS_FK ON NODE_ADAPTERS (
   NODE_ID ASC
)
go
CREATE  INDEX FK_LOAN_CARD_OFFER_TO_LOGINS_F ON LOAN_CARD_OFFER (
   LOGIN_ID ASC
)
go
CREATE  INDEX SUBSCRIB_TO_LOGINS_FK ON SUBSCRIPTIONS (
   LOGIN_ID ASC
)
go
CREATE  INDEX REFERENCE_CONTRACTS_TB_FK ON COUNT_CONTRACTS (
   REPORT_ID ASC
)
go
CREATE  INDEX FK_FORM_PACKAGES_TO_PACKAGE_FK ON FORM_PACKAGES (
   PACKAGE_ID ASC
)
go
CREATE  INDEX REFERENCE_ACTIVE_USRES_VSP_FK ON COUNT_ACTIVE_USERS (
   REPORT_ID ASC
)
go
CREATE  INDEX FK_CARDREST_TO_RESTRICT_FK ON CARDRESTRICTIONS (
   RESTRICTION_ID ASC
)
go
CREATE  INDEX FK_CELLTYPE_FK_CELLTY_TERMS_OF ON CELLTYPES_TERMS_OF_LEASE (
   TERM_OF_LEASE_ID ASC
)
go
CREATE  INDEX FK_ACCOUNTR_TO_RESTRICT_FK ON ACCOUNTRESTRICTIONS (
   RESTRICTION_ID ASC
)
go
CREATE  INDEX FK_UGROUP_SKINS_SKIN_ID_FK ON UGROUP_SKINS (
   SKIN_ID ASC
)
go
CREATE  INDEX FK_FIELDS_TO_PARAM_FK ON FILTER_PARAMETERS_FIELDS (
   FILTER_ID ASC
)
go
CREATE  INDEX FK_SUBTEM_TO_TEMPLATE_FK ON SUBSCRIPTION_TEMPLATES (
   TEMPLATE_ID ASC
)
go
CREATE  INDEX FK_FORM_TEMPLATES_TO_TEMPLATE_ ON FORM_TEMPLATES (
   TEMPLATE_ID ASC
)
go
CREATE  INDEX FK_LOAN_OFFER_TO_DEPARTMENTS_F ON LOAN_OFFER (
   DEPARTMENT_ID ASC
)
go
CREATE  INDEX FK_S_PROVIDERS_TO_DEPARTMENTS_ ON SERVICE_PROVIDERS (
   DEPARTMENT_ID ASC
)
go
CREATE  INDEX FK_CATEGORY_TO_P_SERV_FK ON PAYMENT_SERVICE_CATEGORIES (
   PAYMENT_SERVICES_ID ASC
)
go
CREATE  INDEX FK_PAYMENT_TEMPLATE_PROVIDER_F ON PAYMENT_TEMPLATE_LINKS (
   SERVICE_PROVIDER_ID ASC
)
go
CREATE  INDEX REFERENCE_25_FK ON SHOP_ADDITIONAL_FIELDS (
   SHOP_ORDER_ID ASC
)
go
CREATE  INDEX SCHEDULE_TO_DISTRIBUTION_FK ON SCHEDULE (
   DISTRIBUTION_ID ASC
)
go
CREATE  INDEX FK_PAYMENTSYSTEMLINKS_TO_LOGIN ON PAYMENTS_SYSTEM_LINKS (
   LOGIN_ID ASC
)
go
CREATE  INDEX FK_OFFICE_C_FK_DEPART_CELLTYPE ON OFFICE_CELLTYPES (
   CELLTYPE_ID ASC
)
go
CREATE  INDEX FK_SCHEMEOW_REFERENCE_ACCESSSC ON SCHEMEOWNS (
   SCHEME_ID ASC
)
go
CREATE  INDEX FK_GROUP_EL_TO_LOGINS_FK ON GROUP_ELEMENTS (
   LOGIN_ID ASC
)
go
CREATE  INDEX FK_REGION_TO_REGION_FK ON REGIONS (
   PARENT_ID ASC
)
go
CREATE  INDEX FK_LIMITS_TO_DEPARTMENTS_FK ON LIMITS (
   DEPARTMENT_ID ASC
)
go
CREATE  INDEX FK_LOAN_OFFER_TO_LOGINS_FK ON LOAN_OFFER (
   LOGIN_ID ASC
)
go
CREATE  INDEX REFERENCE_22_FK ON INDIVIDUAL_LIMITS (
   LOGIN_ID ASC
)
go
CREATE  INDEX REFERENCE_3_FK ON LOAN_PRODUCTS (
   DOCUMENTS_PACKAGE_ID ASC
)
go
CREATE  INDEX FK_PROV_REG_TO_REG_FK ON SERVICE_PROVIDER_REGIONS (
   REGION_ID ASC
)
go
CREATE  INDEX REFERENCE_23_FK ON DEFAULT_ACCESS_SCHEMES (
   SCHEME_ID ASC
)
go
CREATE  INDEX FK_DAOF_TO_REG_ADDRESS_FK ON DEPO_ACCOUNT_OWNER_FORM (
   REGISTRATION_ADDRESS ASC
)
go
CREATE  INDEX MAIL_TO_LOGIN_EMPLOYEE_FK ON MAIL (
   EMPLOYEE_ID ASC
)
go
CREATE  INDEX FK_GROUPS_TO_DEPARTMENT_FK ON UGROUP (
   DEPARTMENT_ID ASC
)
go
CREATE  INDEX FK_AUTHMODES_TO_LOGINS_FK ON AUTHENTICATION_MODES (
   LOGIN_ID ASC
)
go
CREATE  INDEX FK_NOTIFICATIONS_TO_LOGINS_FK ON NOTIFICATIONS (
   LOGIN ASC
)
go
CREATE  INDEX SUBSCRIPTIONS_TO_SCHEDULES_FK ON SUBSCRIPTIONS (
   SCHEDULE_ID ASC
)
go
CREATE  INDEX FK_DOCUMENTS_TO_USERS_FK ON DOCUMENTS (
   PERSON_ID ASC
)
go
CREATE  INDEX FK_PROV_PAY_SER_TO_PAY_FK ON SERV_PROVIDER_PAYMENT_SERV (
   PAYMENT_SERVICE_ID ASC
)
go
CREATE  INDEX FK_DEPARTMENTS_TO_ADAPTERS_FK ON DEPARTMENTS (
   ADAPTER_ID ASC
)
go
CREATE  INDEX TEMPLATE_TO_DISTRIBUTION_FK ON MESSAGE_TEMPLATES (
   DISTRIBUTION_ID ASC
)
go
CREATE  INDEX REFERENCE_4_FK ON WORK_DAYS (
   CALENDAR_ID ASC
)
go
CREATE  INDEX FK_P_SERVICE_TO_P_SERVICE_FK ON PAYMENT_SERVICES (
   PARENT_ID ASC
)
go
CREATE  INDEX REFERENCE_21_FK ON RATE (
   FROM_CURRENCY ASC
)
go
CREATE  INDEX FK_PAYMENT_TO_SIGNATURE_FK ON BUSINESS_DOCUMENTS (
   SIGNATURE_ID ASC
)
go
CREATE  INDEX FK_F_VALID_TO_FIELD_FK ON FIELD_VALIDATORS_DESCR (
   FIELD_ID ASC
)
go
CREATE  INDEX FK_CANCELAT_REFERENCE_USERS_FK ON CANCELATION_CALLBACK_LINK (
   PERSON_ID ASC
)
go
CREATE  INDEX REFERENCE_13_FK ON COUNT_OPERATIONS (
   REPORT_ID ASC
)
go
CREATE  INDEX FK_MB_PAYMENT_UPDATE_TO_LOGINS ON MB_PAYMENT_TEMPLATE_UPDATES (
   LOGIN_ID ASC
)
go
CREATE  INDEX REFERENCE_14_FK ON COUNT_BUSINESS_PARAMS_TB (
   REPORT_ID ASC
)
go
CREATE  INDEX FK_ADAPTERS_TO_NODE_ADAPTERS_F ON NODE_ADAPTERS (
   ADAPTER_ID ASC
)
go
CREATE  INDEX FK_OFFICE_C_FK_DEPARTMENTS_FK ON OFFICE_CELLTYPES (
   DEPARTMENT_ID ASC
)
go
CREATE  INDEX FK_ALLOWED_DEP_TO_DEPARTME_FK ON ALLOWED_DEPARTMENT (
   DEPARTMENT_ID ASC
)
go
CREATE  INDEX REFERENCE_18_FK ON RATE (
   TO_CURRENCY ASC
)
go
CREATE  INDEX FK_DAOF_TO_W_ADDRESS_FK ON DEPO_ACCOUNT_OWNER_FORM (
   WORK_ADDRESS ASC
)
go
CREATE  INDEX FK_MENU_LINKS_TO_LOGINS_FK ON MENU_LINKS (
   LOGIN_ID ASC
)
go
CREATE  INDEX RATE_TO_DEPARTMENT_FK ON RATE (
   DEPARTMENT_ID ASC
)
go
CREATE  INDEX FK_CARDLINKS_TO_LOGINS_FK ON CARD_LINKS (
   LOGIN_ID ASC
)
go
CREATE  INDEX REFERENCE_12_FK ON PSEUDONYMS (
   LOGIN_ID ASC
)
go
CREATE  INDEX FK_F_VALUE_TO_FIELD_FK ON FIELD_VALUES_DESCR (
   FIELD_ID ASC
)
go
CREATE  INDEX ELEMENT_TO_PACKAGE_FK ON DOCUMENTS_PACKAGE (
   PACKAGE_ID ASC
)
go
CREATE  INDEX FK_USERS_TO_USERS_FK ON USERS (
   TRUSTING_ID ASC
)
go
CREATE  INDEX FK_PAYMENT_TEMPLATE_LOGIN_FK ON PAYMENT_TEMPLATE_LINKS (
   LOGIN_ID ASC
)
go
CREATE  INDEX ELEMENT_TO_PACKAGE_FK2 ON CLIENTSPACKAGESTEMPLATES (
   PACKAGE_ID ASC
)
go
CREATE  INDEX FK_DEF_SCHEMES_DEPARTMENTS_FK ON DEFAULT_ACCESS_SCHEMES (
   DEPARTMENT_ID ASC
)
go
CREATE  INDEX FK_DAOF_TO_P_ADDRESS_FK ON DEPO_ACCOUNT_OWNER_FORM (
   FOR_PENSION_ADDRESS ASC
)
go
CREATE  INDEX FK_SUBTEM_TO_SUBS_FK ON SUBSCRIPTION_TEMPLATES (
   SUBSCRIPTION_ID ASC
)
go
CREATE  INDEX FK_SCHEMESS_TO_SCHEME_FK ON SCHEMESSERVICES (
   SCHEME_ID ASC
)
go
CREATE  INDEX FK_ACCOUNTLINKS_TO_LOGINS_FK ON ACCOUNT_LINKS (
   LOGIN_ID ASC
)
go
CREATE  INDEX FK_LOAN_C_OFFER_TO_DEPARTMENTS ON LOAN_CARD_OFFER (
   DEPARTMENT_ID ASC
)
go
CREATE  INDEX FK_FORM_PACKAGES_TO_FORM_FK ON FORM_PACKAGES (
   FORM_ID ASC
)
go
CREATE  INDEX FK_LOANLINKS_TO_LOGINS_FK ON LOAN_LINKS (
   LOGIN_ID ASC
)
go
CREATE  INDEX "Reference_4_FK" ON SENDED_ABSTRACTS (
   CARDLINK_ID ASC
)
go
CREATE  INDEX FK_GROUP_ID_FK ON UGROUP_SKINS (
   GROUP_ID ASC
)
go
CREATE  INDEX FK_LONGOFLINKS_TO_LOGINS_FK ON LONG_OFFER_LINKS (
   LOGIN_ID ASC
)
go
CREATE  INDEX FK_LINKS_TO_LOGINS_FK ON FAVOURITE_LINKS (
   LOGIN_ID ASC
)
go
CREATE  INDEX REFERENCE_16_FK ON COUNT_BUSINESS_PARAMS_SBRF (
   REPORT_ID ASC
)
go
CREATE  INDEX FK_USERS_RES_ADDRESS_FK ON USERS (
   RESIDENCE_ADDRESS ASC
)
go
CREATE  INDEX FK_SCHEMEOW_REFERENCE_LOGINS_F ON SCHEMEOWNS (
   LOGIN_ID ASC
)
go
CREATE  INDEX REFERENCE_2_FK ON MAIL (
   SENDER_ID ASC
)
go
CREATE  INDEX FK_USERS_REG_ADDRESS_FK ON USERS (
   REGISTRATION_ADDRESS ASC
)
go
CREATE  INDEX FK_EMPLOYEE_TO_L_OFFICE_FK ON EMPLOYEES (
   LOAN_OFFICE_ID ASC
)
go
CREATE  INDEX FK_PROV_PAY_SER_TO_PROV_FK ON SERV_PROVIDER_PAYMENT_SERV (
   SERVICE_PROVIDER_ID ASC
)
go
CREATE  INDEX FK_DEP_ACC_FK_DAOF_FK ON DEPOSITOR_ACCOUNT (
   DEPOSITOR_ID ASC
)
go
CREATE  INDEX REFERENCE_10_FK ON PAYMENTS_SYSTEM_LINKS (
   BILLING_ID ASC
)
go
CREATE  INDEX FK_ELEMENTS_TO_GROUPS_FK ON GROUP_ELEMENTS (
   GROUP_ID ASC
)
go
CREATE  INDEX FK_FORM_TEMPLATES_TO_FORM_FK ON FORM_TEMPLATES (
   FORM_ID ASC
)
go
CREATE  INDEX REFERENCE_6_FK ON IMACCOUNT_LINKS (
   LOGIN_ID ASC
)
go
CREATE  INDEX FK_CERT_OWN_TO_LOGINS_FK ON CERT_OWN (
   LOGIN_ID ASC
)
go
CREATE  INDEX FK_DPRESTR_TO_RESTRICTION_FK ON DEPPRODUCTRESTRICTIONS (
   RESTRICTION_ID ASC
)
go
