grant aq_user_role to {USER}
go
grant execute on DBMS_AQADM to {USER}
go
GRANT execute ON sys.dbms_aq     TO  {USER}
go
GRANT execute ON sys.dbms_aqin   TO  {USER}
go
GRANT execute ON sys.dbms_aqjms  TO  {USER}
go

begin  
   DBMS_AQADM.GRANT_TYPE_ACCESS('{USER}');
end;  
   
begin  
  dbms_aqadm.grant_system_privilege('ENQUEUE_ANY','{USER}');  
  dbms_aqadm.grant_system_privilege('DEQUEUE_ANY','{USER}');  
end;  