CREATE TABLE NTFNTFY_DBT
(
  ISCUR       INTEGER,
  BRANCH      INTEGER,
  OBJECTTYPE  INTEGER,
  OBJECTID    VARCHAR2(36),
  NOTIFYTYPE  INTEGER,
  NOTIFYDATE  DATE,
  NOTIFYTIME  DATE,
  NOTIFYOPER  INTEGER,
  REFERENC    INTEGER,
  RESERVED    VARCHAR2(192),
  OLDREST     NUMBER(19,4),
  NEWREST     NUMBER(19,4),
  IAPPLICATIONKIND INTEGER,
  APPLICATIONKEY VARCHAR2(30),
  SUMMA       NUMBER(19,4),
  OLDLIMIT    NUMBER(19,4),
  NEWLIMIT    NUMBER(19,4),
  OVERSUM     NUMBER(19,4),
  OVERTOTAL   NUMBER(19,4),
  MINREST     NUMBER(19,4),
  STATUS      VARCHAR2(10),
  ERROR       INTEGER
);

CREATE SEQUENCE NTFNTFY_DBT_SEQ
  START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER NTFNTFY_DBT_AINC
  BEFORE INSERT ON NTFNTFY_DBT
  FOR EACH ROW
DECLARE
BEGIN
  SELECT NTFNTFY_DBT_SEQ.NEXTVAL
    INTO :NEW.REFERENC
  FROM DUAL;
END;
/

CREATE TABLE NTFOBJ_DBT
(
  ISCUR       INTEGER,
  BRANCH      INTEGER,
  OBJECTTYPE  INTEGER,
  OBJECTID    VARCHAR2(36),
  REFERENC    INTEGER,
  RESERVED    VARCHAR2(204)
);

CREATE TABLE NTFOLNK_DBT
(
  ISCUR       INTEGER,
  BRANCH      INTEGER,
  OBJECTTYPE  INTEGER,
  OBJECTID    VARCHAR2(36),
  NOTIFYTYPE  INTEGER,
  REFERENC    INTEGER,
  RESERVED    VARCHAR2(202)
);


CREATE INDEX NTFOBJ_DBT_IND0 ON NTFOBJ_DBT
(ISCUR, BRANCH, OBJECTTYPE, OBJECTID);

CREATE INDEX NTFNTFY_DBT_IND0 ON NTFNTFY_DBT
(ISCUR, BRANCH, OBJECTTYPE, OBJECTID, NOTIFYTYPE);

CREATE INDEX NTFNTFY_DBT_IND1 ON NTFNTFY_DBT
(ISCUR, BRANCH, OBJECTTYPE, OBJECTID, NOTIFYDATE, 
NOTIFYTIME);

CREATE UNIQUE INDEX NTFNTFY_DBT_IND2 ON NTFNTFY_DBT
(REFERENC);

