<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://sbrf.ru/baseproduct/erib/adapter/1" xmlns:sb="http://sbrf.ru/baseproduct/erib/adapter/1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ERIBAdapterWService" targetNamespace="http://sbrf.ru/baseproduct/erib/adapter/1">

	<wsdl:types>
    <xsd:schema xmlns:mrm="http://sbrf.ru/baseproduct/erib/adapter/1" targetNamespace="http://sbrf.ru/baseproduct/erib/adapter/1" xmlns:sb="http://sbrf.ru/baseproduct/erib/adapter/1" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <xsd:include schemaLocation="esberib.xsd"/>
    </xsd:schema>
  </wsdl:types>
	<wsdl:message name="DoIFXRqMsg">
		<wsdl:part element="ns:DoIFXRq" name="parameters"/>
	</wsdl:message>
	<wsdl:message name="DoIFXRsMsg">
		<wsdl:part element="ns:DoIFXRs" name="result"/>
	</wsdl:message>
	<wsdl:portType name="EsbEribBackService">
		<wsdl:operation name="DoIFX">
			<wsdl:input message="ns:DoIFXRqMsg"/>
			<wsdl:output message="ns:DoIFXRsMsg"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="EsbEribBackService" type="ns:EsbEribBackService">
		<soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="DoIFX">
			<soap:operation soapAction="http://sbrf.ru/baseproduct/erib/adapter/DoIFX" style="document"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="EsbEribBackService">
		<wsdl:port binding="ns:EsbEribBackService" name="EsbEribBackService">
			<soap:address location="http://localhost:8888/services/EsbEribBackService"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>