// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.streaming.*;

import javax.xml.namespace.QName;
import java.util.ArrayList;

public class ArrayOfXsbResult_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_XsbResult_QNAME = new QName("", "XsbResult");
    private static final javax.xml.namespace.QName ns3_XsbResult_TYPE_QNAME = new QName("http://common.xsb.webservices.bars.sbrf", "XsbResult");
    private CombinedSerializer ns3_myXsbResult_LiteralSerializer;
    
    public ArrayOfXsbResult_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public ArrayOfXsbResult_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns3_myXsbResult_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.rssl.phizicgate.bars.ws.jaxrpc.XsbResult.class, ns3_XsbResult_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbResult instance = new com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbResult();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_XsbResult_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_XsbResult_QNAME))) {
                    value = ns3_myXsbResult_LiteralSerializer.deserialize(ns1_XsbResult_QNAME, reader, context);
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbResult[values.size()];
            member = values.toArray((Object[]) member);
            instance.setXsbResult((com.rssl.phizicgate.bars.ws.jaxrpc.XsbResult[])member);
        }
        else {
            instance.setXsbResult(new com.rssl.phizicgate.bars.ws.jaxrpc.XsbResult[0]);
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbResult instance = (com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbResult)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbResult instance = (com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbResult)obj;
        
        if (instance.getXsbResult() != null) {
            for (int i = 0; i < instance.getXsbResult().length; ++i) {
                ns3_myXsbResult_LiteralSerializer.serialize(instance.getXsbResult()[i], ns1_XsbResult_QNAME, null, writer, context);
            }
        }
    }
}
