// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;


public class ArrayOfXsbChecksDocResults {
    protected com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksDocResults[] xsbChecksDocResults;
    
    public ArrayOfXsbChecksDocResults() {
    }
    
    public ArrayOfXsbChecksDocResults(com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksDocResults[] xsbChecksDocResults) {
        this.xsbChecksDocResults = xsbChecksDocResults;
    }
    
    public com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksDocResults[] getXsbChecksDocResults() {
        return xsbChecksDocResults;
    }
    
    public void setXsbChecksDocResults(com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksDocResults[] xsbChecksDocResults) {
        this.xsbChecksDocResults = xsbChecksDocResults;
    }
}
