// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.streaming.*;

import javax.xml.namespace.QName;
import java.util.ArrayList;

public class ArrayOfXsbChecksDocResults_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_XsbChecksDocResults_QNAME = new QName("", "XsbChecksDocResults");
    private static final javax.xml.namespace.QName ns4_XsbChecksDocResults_TYPE_QNAME = new QName("http://checks.xsb.webservices.bars.sbrf", "XsbChecksDocResults");
    private CombinedSerializer ns4_myXsbChecksDocResults_LiteralSerializer;
    
    public ArrayOfXsbChecksDocResults_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public ArrayOfXsbChecksDocResults_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns4_myXsbChecksDocResults_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksDocResults.class, ns4_XsbChecksDocResults_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbChecksDocResults instance = new com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbChecksDocResults();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_XsbChecksDocResults_QNAME))) {
            values = new ArrayList();
            for(;;) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_XsbChecksDocResults_QNAME))) {
                    value = ns4_myXsbChecksDocResults_LiteralSerializer.deserialize(ns1_XsbChecksDocResults_QNAME, reader, context);
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksDocResults[values.size()];
            member = values.toArray((Object[]) member);
            instance.setXsbChecksDocResults((com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksDocResults[])member);
        }
        else {
            instance.setXsbChecksDocResults(new com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksDocResults[0]);
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbChecksDocResults instance = (com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbChecksDocResults)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbChecksDocResults instance = (com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbChecksDocResults)obj;
        
        if (instance.getXsbChecksDocResults() != null) {
            for (int i = 0; i < instance.getXsbChecksDocResults().length; ++i) {
                ns4_myXsbChecksDocResults_LiteralSerializer.serialize(instance.getXsbChecksDocResults()[i], ns1_XsbChecksDocResults_QNAME, null, writer, context);
            }
        }
    }
}
