// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;


public class ArrayOfXsbRemoteClientNameExtendedResult {
    protected com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedResult[] xsbRemoteClientNameExtendedResult;
    
    public ArrayOfXsbRemoteClientNameExtendedResult() {
    }
    
    public ArrayOfXsbRemoteClientNameExtendedResult(com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedResult[] xsbRemoteClientNameExtendedResult) {
        this.xsbRemoteClientNameExtendedResult = xsbRemoteClientNameExtendedResult;
    }
    
    public com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedResult[] getXsbRemoteClientNameExtendedResult() {
        return xsbRemoteClientNameExtendedResult;
    }
    
    public void setXsbRemoteClientNameExtendedResult(com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedResult[] xsbRemoteClientNameExtendedResult) {
        this.xsbRemoteClientNameExtendedResult = xsbRemoteClientNameExtendedResult;
    }
}
