// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;


public class ArrayOfXsbRemoteClientNameResult {
    protected com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameResult[] xsbRemoteClientNameResult;
    
    public ArrayOfXsbRemoteClientNameResult() {
    }
    
    public ArrayOfXsbRemoteClientNameResult(com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameResult[] xsbRemoteClientNameResult) {
        this.xsbRemoteClientNameResult = xsbRemoteClientNameResult;
    }
    
    public com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameResult[] getXsbRemoteClientNameResult() {
        return xsbRemoteClientNameResult;
    }
    
    public void setXsbRemoteClientNameResult(com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameResult[] xsbRemoteClientNameResult) {
        this.xsbRemoteClientNameResult = xsbRemoteClientNameResult;
    }
}
