// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;


public class ArrayOfXsbExceptionItem {
    protected com.rssl.phizicgate.bars.ws.jaxrpc.XsbExceptionItem[] xsbExceptionItem;
    
    public ArrayOfXsbExceptionItem() {
    }
    
    public ArrayOfXsbExceptionItem(com.rssl.phizicgate.bars.ws.jaxrpc.XsbExceptionItem[] xsbExceptionItem) {
        this.xsbExceptionItem = xsbExceptionItem;
    }
    
    public com.rssl.phizicgate.bars.ws.jaxrpc.XsbExceptionItem[] getXsbExceptionItem() {
        return xsbExceptionItem;
    }
    
    public void setXsbExceptionItem(com.rssl.phizicgate.bars.ws.jaxrpc.XsbExceptionItem[] xsbExceptionItem) {
        this.xsbExceptionItem = xsbExceptionItem;
    }
}
