// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;


public class ArrayOfXsbParameter {
    protected com.rssl.phizicgate.bars.ws.jaxrpc.XsbParameter[] xsbParameter;
    
    public ArrayOfXsbParameter() {
    }
    
    public ArrayOfXsbParameter(com.rssl.phizicgate.bars.ws.jaxrpc.XsbParameter[] xsbParameter) {
        this.xsbParameter = xsbParameter;
    }
    
    public com.rssl.phizicgate.bars.ws.jaxrpc.XsbParameter[] getXsbParameter() {
        return xsbParameter;
    }
    
    public void setXsbParameter(com.rssl.phizicgate.bars.ws.jaxrpc.XsbParameter[] xsbParameter) {
        this.xsbParameter = xsbParameter;
    }
}
