// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;


public class ArrayOfXsbResult {
    protected com.rssl.phizicgate.bars.ws.jaxrpc.XsbResult[] xsbResult;
    
    public ArrayOfXsbResult() {
    }
    
    public ArrayOfXsbResult(com.rssl.phizicgate.bars.ws.jaxrpc.XsbResult[] xsbResult) {
        this.xsbResult = xsbResult;
    }
    
    public com.rssl.phizicgate.bars.ws.jaxrpc.XsbResult[] getXsbResult() {
        return xsbResult;
    }
    
    public void setXsbResult(com.rssl.phizicgate.bars.ws.jaxrpc.XsbResult[] xsbResult) {
        this.xsbResult = xsbResult;
    }
}
