// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;


public class CheckRemoteClientNameResponse {
    protected com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksReturn checkRemoteClientNameReturn;
    
    public CheckRemoteClientNameResponse() {
    }
    
    public CheckRemoteClientNameResponse(com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksReturn checkRemoteClientNameReturn) {
        this.checkRemoteClientNameReturn = checkRemoteClientNameReturn;
    }
    
    public com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksReturn getCheckRemoteClientNameReturn() {
        return checkRemoteClientNameReturn;
    }
    
    public void setCheckRemoteClientNameReturn(com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksReturn checkRemoteClientNameReturn) {
        this.checkRemoteClientNameReturn = checkRemoteClientNameReturn;
    }
}
