// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.streaming.*;

import javax.xml.namespace.QName;

public class CheckRemoteClientNameResponse_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_checkRemoteClientNameReturn_QNAME = new QName("", "checkRemoteClientNameReturn");
    private static final javax.xml.namespace.QName ns4_XsbChecksReturn_TYPE_QNAME = new QName("http://checks.xsb.webservices.bars.sbrf", "XsbChecksReturn");
    private CombinedSerializer ns4_myXsbChecksReturn_LiteralSerializer;
    
    public CheckRemoteClientNameResponse_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public CheckRemoteClientNameResponse_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns4_myXsbChecksReturn_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksReturn.class, ns4_XsbChecksReturn_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.CheckRemoteClientNameResponse instance = new com.rssl.phizicgate.bars.ws.jaxrpc.CheckRemoteClientNameResponse();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_checkRemoteClientNameReturn_QNAME)) {
                member = ns4_myXsbChecksReturn_LiteralSerializer.deserialize(ns1_checkRemoteClientNameReturn_QNAME, reader, context);
                instance.setCheckRemoteClientNameReturn((com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksReturn)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_checkRemoteClientNameReturn_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.CheckRemoteClientNameResponse instance = (com.rssl.phizicgate.bars.ws.jaxrpc.CheckRemoteClientNameResponse)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.CheckRemoteClientNameResponse instance = (com.rssl.phizicgate.bars.ws.jaxrpc.CheckRemoteClientNameResponse)obj;
        
        ns4_myXsbChecksReturn_LiteralSerializer.serialize(instance.getCheckRemoteClientNameReturn(), ns1_checkRemoteClientNameReturn_QNAME, null, writer, context);
    }
}
