// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;


public class ReadRemoteClientNameExtended {
    protected java.lang.String xsbDocument;
    protected com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbParameter parameters;
    
    public ReadRemoteClientNameExtended() {
    }
    
    public ReadRemoteClientNameExtended(java.lang.String xsbDocument, com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbParameter parameters) {
        this.xsbDocument = xsbDocument;
        this.parameters = parameters;
    }
    
    public java.lang.String getXsbDocument() {
        return xsbDocument;
    }
    
    public void setXsbDocument(java.lang.String xsbDocument) {
        this.xsbDocument = xsbDocument;
    }
    
    public com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbParameter getParameters() {
        return parameters;
    }
    
    public void setParameters(com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbParameter parameters) {
        this.parameters = parameters;
    }
}
