// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;


public class ReadRemoteClientNameExtendedResponse {
    protected com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedReturn readRemoteClientNameExtendedReturn;
    
    public ReadRemoteClientNameExtendedResponse() {
    }
    
    public ReadRemoteClientNameExtendedResponse(com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedReturn readRemoteClientNameExtendedReturn) {
        this.readRemoteClientNameExtendedReturn = readRemoteClientNameExtendedReturn;
    }
    
    public com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedReturn getReadRemoteClientNameExtendedReturn() {
        return readRemoteClientNameExtendedReturn;
    }
    
    public void setReadRemoteClientNameExtendedReturn(com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedReturn readRemoteClientNameExtendedReturn) {
        this.readRemoteClientNameExtendedReturn = readRemoteClientNameExtendedReturn;
    }
}
