// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;


public class ReadRemoteClientNameResponse {
    protected com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameReturn readRemoteClientNameReturn;
    
    public ReadRemoteClientNameResponse() {
    }
    
    public ReadRemoteClientNameResponse(com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameReturn readRemoteClientNameReturn) {
        this.readRemoteClientNameReturn = readRemoteClientNameReturn;
    }
    
    public com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameReturn getReadRemoteClientNameReturn() {
        return readRemoteClientNameReturn;
    }
    
    public void setReadRemoteClientNameReturn(com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameReturn readRemoteClientNameReturn) {
        this.readRemoteClientNameReturn = readRemoteClientNameReturn;
    }
}
