// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;

public interface XsbCheckNames extends java.rmi.Remote {
    public com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksReturn checkRemoteClientName(java.lang.String xsbDocument, com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbParameter parameters) throws
         java.rmi.RemoteException;
    public com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameReturn readRemoteClientName(java.lang.String xsbDocument, com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbParameter parameters) throws
         java.rmi.RemoteException;
    public com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedReturn readRemoteClientNameExtended(java.lang.String xsbDocument, com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbParameter parameters) throws
         java.rmi.RemoteException;
}
