// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;

import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.*;
import com.sun.xml.rpc.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.namespace.QName;

public class XsbCheckNamesService_Impl extends com.sun.xml.rpc.client.BasicService implements XsbCheckNamesService {
    private static final QName serviceName = new QName("http://checkNames.xsb.webservices.bars.sbrf", "XsbCheckNamesService");
    private static final QName ns1_XsbCheckNames_QNAME = new QName("http://checkNames.xsb.webservices.bars.sbrf", "XsbCheckNames");
    private static final Class xsbCheckNames_PortClass = com.rssl.phizicgate.bars.ws.jaxrpc.XsbCheckNames.class;
    
    public XsbCheckNamesService_Impl() {
        super(serviceName, new QName[] {
                        ns1_XsbCheckNames_QNAME
                    },
            new com.rssl.phizicgate.bars.ws.jaxrpc.XsbCheckNamesService_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(javax.xml.namespace.QName portName, java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_XsbCheckNames_QNAME) &&
                serviceDefInterface.equals(xsbCheckNames_PortClass)) {
                return getXsbCheckNames();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(xsbCheckNames_PortClass)) {
                return getXsbCheckNames();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public com.rssl.phizicgate.bars.ws.jaxrpc.XsbCheckNames getXsbCheckNames() {
        java.lang.String[] roles = new java.lang.String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_XsbCheckNames_QNAME));
        handlerChain.setRoles(roles);
        com.rssl.phizicgate.bars.ws.jaxrpc.XsbCheckNames_Stub stub = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbCheckNames_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
