// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;


public class XsbChecksDocResults extends com.rssl.phizicgate.bars.ws.jaxrpc.XsbDocResults {
    protected com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbResult checks;
    
    public XsbChecksDocResults() {
    }
    
    public XsbChecksDocResults(com.rssl.phizicgate.bars.ws.jaxrpc.XsbDocID docID, com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbExceptionItem exceptionItems, com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbResult checks) {
        this.docID = docID;
        this.exceptionItems = exceptionItems;
        this.checks = checks;
    }
    
    public com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbResult getChecks() {
        return checks;
    }
    
    public void setChecks(com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbResult checks) {
        this.checks = checks;
    }
}
