// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;

import com.sun.xml.rpc.client.BasicService;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.*;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;

import javax.xml.rpc.encoding.*;
import javax.xml.namespace.QName;

public class XsbCheckNamesService_SerializerRegistry implements SerializerConstants {
    public XsbCheckNamesService_SerializerRegistry() {
    }
    
    public TypeMappingRegistry getRegistry() {
        
        TypeMappingRegistry registry = BasicService.createStandardTypeMappingRegistry();
        TypeMapping mapping12 = registry.getTypeMapping(SOAP12Constants.NS_SOAP_ENCODING);
        TypeMapping mapping = registry.getTypeMapping(SOAPConstants.NS_SOAP_ENCODING);
        TypeMapping mapping2 = registry.getTypeMapping("");
        {
            QName type = new QName("http://common.xsb.webservices.bars.sbrf", "ArrayOfXsbResult");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbResult_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbResult.class, type, serializer);
        }
        {
            QName type = new QName("http://checkNames.xsb.webservices.bars.sbrf", "checkRemoteClientName");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.CheckRemoteClientName_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.CheckRemoteClientName.class, type, serializer);
        }
        {
            QName type = new QName("http://common.xsb.webservices.bars.sbrf", "XsbParameter");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbParameter_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.XsbParameter.class, type, serializer);
        }
        {
            QName type = new QName("http://checks.xsb.webservices.bars.sbrf", "ArrayOfXsbChecksDocResults");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbChecksDocResults_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbChecksDocResults.class, type, serializer);
        }
        {
            QName type = new QName("http://checkNames.xsb.webservices.bars.sbrf", "readRemoteClientNameExtendedResponse");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.ReadRemoteClientNameExtendedResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.ReadRemoteClientNameExtendedResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://checkNames.xsb.webservices.bars.sbrf", "ArrayOfXsbRemoteClientNameExtendedResult");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbRemoteClientNameExtendedResult_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbRemoteClientNameExtendedResult.class, type, serializer);
        }
        {
            QName type = new QName("http://checkNames.xsb.webservices.bars.sbrf", "readRemoteClientName");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.ReadRemoteClientName_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.ReadRemoteClientName.class, type, serializer);
        }
        {
            QName type = new QName("http://common.xsb.webservices.bars.sbrf", "ArrayOfXsbParameter");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbParameter_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbParameter.class, type, serializer);
        }
        {
            QName type = new QName("http://common.xsb.webservices.bars.sbrf", "XsbReturn");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbReturn_InterfaceSOAPSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.XsbReturn.class, type, serializer);
        }
        {
            QName type = new QName("http://checkNames.xsb.webservices.bars.sbrf", "checkRemoteClientNameResponse");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.CheckRemoteClientNameResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.CheckRemoteClientNameResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://common.xsb.webservices.bars.sbrf", "ArrayOfXsbExceptionItem");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbExceptionItem_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbExceptionItem.class, type, serializer);
        }
        {
            QName type = new QName("http://checks.xsb.webservices.bars.sbrf", "XsbChecksReturn");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksReturn_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksReturn.class, type, serializer);
        }
        {
            QName type = new QName("http://checkNames.xsb.webservices.bars.sbrf", "XsbRemoteClientNameResult");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameResult_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameResult.class, type, serializer);
        }
        {
            CombinedSerializer serializer = new LiteralFragmentSerializer(SchemaConstants.QNAME_TYPE_URTYPE, NOT_NULLABLE, "");
            registerSerializer(mapping2,javax.xml.soap.SOAPElement.class, SchemaConstants.QNAME_TYPE_URTYPE, serializer);
        }
        {
            QName type = new QName("http://checkNames.xsb.webservices.bars.sbrf", "XsbRemoteClientNameReturn");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameReturn_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameReturn.class, type, serializer);
        }
        {
            QName type = new QName("http://common.xsb.webservices.bars.sbrf", "XsbExceptionItem");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbExceptionItem_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.XsbExceptionItem.class, type, serializer);
        }
        {
            QName type = new QName("http://checkNames.xsb.webservices.bars.sbrf", "XsbRemoteClientNameExtendedResult");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedResult_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedResult.class, type, serializer);
        }
        {
            QName type = new QName("http://common.xsb.webservices.bars.sbrf", "XsbDocID");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbDocID_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.XsbDocID.class, type, serializer);
        }
        {
            QName type = new QName("http://checkNames.xsb.webservices.bars.sbrf", "ArrayOfXsbRemoteClientNameResult");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbRemoteClientNameResult_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbRemoteClientNameResult.class, type, serializer);
        }
        {
            QName type = new QName("http://checkNames.xsb.webservices.bars.sbrf", "readRemoteClientNameResponse");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.ReadRemoteClientNameResponse_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.ReadRemoteClientNameResponse.class, type, serializer);
        }
        {
            QName type = new QName("http://checkNames.xsb.webservices.bars.sbrf", "XsbRemoteClientNameExtendedReturn");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedReturn_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedReturn.class, type, serializer);
        }
        {
            QName type = new QName("http://common.xsb.webservices.bars.sbrf", "XsbResult");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbResult_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.XsbResult.class, type, serializer);
        }
        {
            QName type = new QName("http://checks.xsb.webservices.bars.sbrf", "XsbChecksDocResults");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksDocResults_LiteralSerializer(type, "", ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksDocResults.class, type, serializer);
        }
        {
            QName type = new QName("http://checkNames.xsb.webservices.bars.sbrf", "readRemoteClientNameExtended");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.ReadRemoteClientNameExtended_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.ReadRemoteClientNameExtended.class, type, serializer);
        }
        {
            QName type = new QName("http://common.xsb.webservices.bars.sbrf", "XsbDocResults");
            CombinedSerializer serializer = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbDocResults_InterfaceSOAPSerializer(type, "", DONT_ENCODE_TYPE);
            registerSerializer(mapping2, com.rssl.phizicgate.bars.ws.jaxrpc.XsbDocResults.class, type, serializer);
        }
        return registry;
    }
    
    private static void registerSerializer(TypeMapping mapping, java.lang.Class javaType, javax.xml.namespace.QName xmlType,
        Serializer ser) {
        mapping.register(javaType, xmlType, new SingletonSerializerFactory(ser),
            new SingletonDeserializerFactory((Deserializer)ser));
    }
    
}
