// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;

import javax.xml.rpc.*;

public interface XsbCheckNamesService extends javax.xml.rpc.Service {
    public com.rssl.phizicgate.bars.ws.jaxrpc.XsbCheckNames getXsbCheckNames() throws ServiceException;
}
