// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;


public class XsbDocResults {
    protected com.rssl.phizicgate.bars.ws.jaxrpc.XsbDocID docID;
    protected com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbExceptionItem exceptionItems;
    
    public XsbDocResults() {
    }
    
    public XsbDocResults(com.rssl.phizicgate.bars.ws.jaxrpc.XsbDocID docID, com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbExceptionItem exceptionItems) {
        this.docID = docID;
        this.exceptionItems = exceptionItems;
    }
    
    public com.rssl.phizicgate.bars.ws.jaxrpc.XsbDocID getDocID() {
        return docID;
    }
    
    public void setDocID(com.rssl.phizicgate.bars.ws.jaxrpc.XsbDocID docID) {
        this.docID = docID;
    }
    
    public com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbExceptionItem getExceptionItems() {
        return exceptionItems;
    }
    
    public void setExceptionItems(com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbExceptionItem exceptionItems) {
        this.exceptionItems = exceptionItems;
    }
}
