// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;


public class XsbExceptionItem {
    protected java.lang.String excMessage;
    protected java.lang.String excName;
    
    public XsbExceptionItem() {
    }
    
    public XsbExceptionItem(java.lang.String excMessage, java.lang.String excName) {
        this.excMessage = excMessage;
        this.excName = excName;
    }
    
    public java.lang.String getExcMessage() {
        return excMessage;
    }
    
    public void setExcMessage(java.lang.String excMessage) {
        this.excMessage = excMessage;
    }
    
    public java.lang.String getExcName() {
        return excName;
    }
    
    public void setExcName(java.lang.String excName) {
        this.excName = excName;
    }
}
