// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.streaming.*;

import javax.xml.namespace.QName;

public class XsbReturn_InterfaceSOAPSerializer extends InterfaceSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_XsbChecksReturn_TYPE_QNAME = new QName("http://checks.xsb.webservices.bars.sbrf", "XsbChecksReturn");
    private CombinedSerializer ns1_myXsbChecksReturn_LiteralSerializer;
    private static final javax.xml.namespace.QName ns2_XsbRemoteClientNameExtendedReturn_TYPE_QNAME = new QName("http://checkNames.xsb.webservices.bars.sbrf", "XsbRemoteClientNameExtendedReturn");
    private CombinedSerializer ns2_myXsbRemoteClientNameExtendedReturn_LiteralSerializer;
    private static final javax.xml.namespace.QName ns2_XsbRemoteClientNameReturn_TYPE_QNAME = new QName("http://checkNames.xsb.webservices.bars.sbrf", "XsbRemoteClientNameReturn");
    private CombinedSerializer ns2_myXsbRemoteClientNameReturn_LiteralSerializer;
    private CombinedSerializer ns3_myXsbReturn_LiteralSerializer;
    
    public XsbReturn_InterfaceSOAPSerializer(QName type, String encodingStyle, boolean encodeType) {
        super(type, encodeType, true, encodingStyle);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns1_myXsbChecksReturn_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksReturn.class, ns1_XsbChecksReturn_TYPE_QNAME);
        ns1_myXsbChecksReturn_LiteralSerializer = ns1_myXsbChecksReturn_LiteralSerializer.getInnermostSerializer();
        ns2_myXsbRemoteClientNameExtendedReturn_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedReturn.class, ns2_XsbRemoteClientNameExtendedReturn_TYPE_QNAME);
        ns2_myXsbRemoteClientNameExtendedReturn_LiteralSerializer = ns2_myXsbRemoteClientNameExtendedReturn_LiteralSerializer.getInnermostSerializer();
        ns2_myXsbRemoteClientNameReturn_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameReturn.class, ns2_XsbRemoteClientNameReturn_TYPE_QNAME);
        ns2_myXsbRemoteClientNameReturn_LiteralSerializer = ns2_myXsbRemoteClientNameReturn_LiteralSerializer.getInnermostSerializer();
        QName type = new QName("http://common.xsb.webservices.bars.sbrf", "XsbReturn");
        CombinedSerializer interfaceSerializer = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbReturn_LiteralSerializer(type, "", DONT_ENCODE_TYPE);
        ns3_myXsbReturn_LiteralSerializer = interfaceSerializer.getInnermostSerializer();
        if (ns3_myXsbReturn_LiteralSerializer instanceof Initializable) {
            ((Initializable)ns3_myXsbReturn_LiteralSerializer).initialize(registry);
        }
    }
    
    public java.lang.Object doDeserialize(javax.xml.namespace.QName name, XMLReader reader,
        SOAPDeserializationContext context) throws Exception {
        javax.xml.namespace.QName elementType = getType(reader);
        if (elementType != null && elementType.equals(ns1_myXsbChecksReturn_LiteralSerializer.getXmlType())) {
            return ns1_myXsbChecksReturn_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(ns2_myXsbRemoteClientNameExtendedReturn_LiteralSerializer.getXmlType())) {
            return ns2_myXsbRemoteClientNameExtendedReturn_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType != null && elementType.equals(ns2_myXsbRemoteClientNameReturn_LiteralSerializer.getXmlType())) {
            return ns2_myXsbRemoteClientNameReturn_LiteralSerializer.deserialize(name, reader, context);
        } else if (elementType == null || elementType.equals(ns3_myXsbReturn_LiteralSerializer.getXmlType())) {
            Object obj = ns3_myXsbReturn_LiteralSerializer.deserialize(name, reader, context);
            return obj;
        }
        throw new DeserializationException("soap.unexpectedElementType", new Object[] {"", elementType.toString()});
    }
    
    public void doSerializeInstance(java.lang.Object obj, javax.xml.namespace.QName name, SerializerCallback callback,
        XMLWriter writer, SOAPSerializationContext context) throws Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.XsbReturn instance = (com.rssl.phizicgate.bars.ws.jaxrpc.XsbReturn)obj;
        
        if (obj instanceof com.rssl.phizicgate.bars.ws.jaxrpc.XsbChecksReturn) {
            ns1_myXsbChecksReturn_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedReturn) {
            ns2_myXsbRemoteClientNameExtendedReturn_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else if (obj instanceof com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameReturn) {
            ns2_myXsbRemoteClientNameReturn_LiteralSerializer.serialize(obj, name, callback, writer, context);
        } else {
            ns3_myXsbReturn_LiteralSerializer.serialize(obj, name, callback, writer, context);
        }
    }
}
