// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.streaming.*;

import javax.xml.namespace.QName;

public class XsbRemoteClientNameExtendedReturn_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_exceptionItems_QNAME = new QName("", "exceptionItems");
    private static final javax.xml.namespace.QName ns3_ArrayOfXsbExceptionItem_TYPE_QNAME = new QName("http://common.xsb.webservices.bars.sbrf", "ArrayOfXsbExceptionItem");
    private CombinedSerializer ns3_myArrayOfXsbExceptionItem_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_documents_QNAME = new QName("", "documents");
    private static final javax.xml.namespace.QName ns5_ArrayOfXsbRemoteClientNameExtendedResult_TYPE_QNAME = new QName("http://checkNames.xsb.webservices.bars.sbrf", "ArrayOfXsbRemoteClientNameExtendedResult");
    private CombinedSerializer ns5_myArrayOfXsbRemoteClientNameExtendedResult_LiteralSerializer;
    
    public XsbRemoteClientNameExtendedReturn_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public XsbRemoteClientNameExtendedReturn_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns3_myArrayOfXsbExceptionItem_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbExceptionItem.class, ns3_ArrayOfXsbExceptionItem_TYPE_QNAME);
        ns5_myArrayOfXsbRemoteClientNameExtendedResult_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbRemoteClientNameExtendedResult.class, ns5_ArrayOfXsbRemoteClientNameExtendedResult_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedReturn instance = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedReturn();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_exceptionItems_QNAME)) {
                member = ns3_myArrayOfXsbExceptionItem_LiteralSerializer.deserialize(ns1_exceptionItems_QNAME, reader, context);
                instance.setExceptionItems((com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbExceptionItem)member);
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_documents_QNAME)) {
                member = ns5_myArrayOfXsbRemoteClientNameExtendedResult_LiteralSerializer.deserialize(ns1_documents_QNAME, reader, context);
                instance.setDocuments((com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbRemoteClientNameExtendedResult)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_documents_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedReturn instance = (com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedReturn)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedReturn instance = (com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedReturn)obj;
        
        ns3_myArrayOfXsbExceptionItem_LiteralSerializer.serialize(instance.getExceptionItems(), ns1_exceptionItems_QNAME, null, writer, context);
        ns5_myArrayOfXsbRemoteClientNameExtendedResult_LiteralSerializer.serialize(instance.getDocuments(), ns1_documents_QNAME, null, writer, context);
    }
}
