// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;


public class XsbRemoteClientNameExtendedResult extends com.rssl.phizicgate.bars.ws.jaxrpc.XsbDocResults {
    protected javax.xml.soap.SOAPElement DOldNameBeg;
    protected javax.xml.soap.SOAPElement DOldNameEnd;
    protected java.lang.String SFName;
    protected java.lang.String SFNameOld;
    protected java.lang.String SInn;
    protected java.lang.String SSName;
    protected java.lang.String SSNameOld;
    protected java.lang.String SNumRegister;
    protected javax.xml.soap.SOAPElement DDateRegister;
    protected java.lang.String SOkpo;
    protected java.lang.String SAddressRegister;
    protected java.lang.String SCountry;
    protected java.lang.String SIndex;
    protected java.lang.String SStreet;
    protected java.lang.String SHouse;
    protected java.lang.String SCorps;
    protected java.lang.String SBuilding;
    protected java.lang.String SFlat;
    protected java.lang.String SOffice;
    protected java.lang.String SStreetE;
    protected java.lang.String SCity;
    protected java.lang.String SRegion;
    protected java.lang.String SAdrType;
    protected java.lang.String SAdrTypeName;
    
    public XsbRemoteClientNameExtendedResult() {
    }
    
    public XsbRemoteClientNameExtendedResult(com.rssl.phizicgate.bars.ws.jaxrpc.XsbDocID docID, com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbExceptionItem exceptionItems, javax.xml.soap.SOAPElement DOldNameBeg, javax.xml.soap.SOAPElement DOldNameEnd, java.lang.String SFName, java.lang.String SFNameOld, java.lang.String SInn, java.lang.String SSName, java.lang.String SSNameOld, java.lang.String SNumRegister, javax.xml.soap.SOAPElement DDateRegister, java.lang.String SOkpo, java.lang.String SAddressRegister, java.lang.String SCountry, java.lang.String SIndex, java.lang.String SStreet, java.lang.String SHouse, java.lang.String SCorps, java.lang.String SBuilding, java.lang.String SFlat, java.lang.String SOffice, java.lang.String SStreetE, java.lang.String SCity, java.lang.String SRegion, java.lang.String SAdrType, java.lang.String SAdrTypeName) {
        this.docID = docID;
        this.exceptionItems = exceptionItems;
        this.DOldNameBeg = DOldNameBeg;
        this.DOldNameEnd = DOldNameEnd;
        this.SFName = SFName;
        this.SFNameOld = SFNameOld;
        this.SInn = SInn;
        this.SSName = SSName;
        this.SSNameOld = SSNameOld;
        this.SNumRegister = SNumRegister;
        this.DDateRegister = DDateRegister;
        this.SOkpo = SOkpo;
        this.SAddressRegister = SAddressRegister;
        this.SCountry = SCountry;
        this.SIndex = SIndex;
        this.SStreet = SStreet;
        this.SHouse = SHouse;
        this.SCorps = SCorps;
        this.SBuilding = SBuilding;
        this.SFlat = SFlat;
        this.SOffice = SOffice;
        this.SStreetE = SStreetE;
        this.SCity = SCity;
        this.SRegion = SRegion;
        this.SAdrType = SAdrType;
        this.SAdrTypeName = SAdrTypeName;
    }
    
    public javax.xml.soap.SOAPElement getDOldNameBeg() {
        return DOldNameBeg;
    }
    
    public void setDOldNameBeg(javax.xml.soap.SOAPElement DOldNameBeg) {
        this.DOldNameBeg = DOldNameBeg;
    }
    
    public javax.xml.soap.SOAPElement getDOldNameEnd() {
        return DOldNameEnd;
    }
    
    public void setDOldNameEnd(javax.xml.soap.SOAPElement DOldNameEnd) {
        this.DOldNameEnd = DOldNameEnd;
    }
    
    public java.lang.String getSFName() {
        return SFName;
    }
    
    public void setSFName(java.lang.String SFName) {
        this.SFName = SFName;
    }
    
    public java.lang.String getSFNameOld() {
        return SFNameOld;
    }
    
    public void setSFNameOld(java.lang.String SFNameOld) {
        this.SFNameOld = SFNameOld;
    }
    
    public java.lang.String getSInn() {
        return SInn;
    }
    
    public void setSInn(java.lang.String SInn) {
        this.SInn = SInn;
    }
    
    public java.lang.String getSSName() {
        return SSName;
    }
    
    public void setSSName(java.lang.String SSName) {
        this.SSName = SSName;
    }
    
    public java.lang.String getSSNameOld() {
        return SSNameOld;
    }
    
    public void setSSNameOld(java.lang.String SSNameOld) {
        this.SSNameOld = SSNameOld;
    }
    
    public java.lang.String getSNumRegister() {
        return SNumRegister;
    }
    
    public void setSNumRegister(java.lang.String SNumRegister) {
        this.SNumRegister = SNumRegister;
    }
    
    public javax.xml.soap.SOAPElement getDDateRegister() {
        return DDateRegister;
    }
    
    public void setDDateRegister(javax.xml.soap.SOAPElement DDateRegister) {
        this.DDateRegister = DDateRegister;
    }
    
    public java.lang.String getSOkpo() {
        return SOkpo;
    }
    
    public void setSOkpo(java.lang.String SOkpo) {
        this.SOkpo = SOkpo;
    }
    
    public java.lang.String getSAddressRegister() {
        return SAddressRegister;
    }
    
    public void setSAddressRegister(java.lang.String SAddressRegister) {
        this.SAddressRegister = SAddressRegister;
    }
    
    public java.lang.String getSCountry() {
        return SCountry;
    }
    
    public void setSCountry(java.lang.String SCountry) {
        this.SCountry = SCountry;
    }
    
    public java.lang.String getSIndex() {
        return SIndex;
    }
    
    public void setSIndex(java.lang.String SIndex) {
        this.SIndex = SIndex;
    }
    
    public java.lang.String getSStreet() {
        return SStreet;
    }
    
    public void setSStreet(java.lang.String SStreet) {
        this.SStreet = SStreet;
    }
    
    public java.lang.String getSHouse() {
        return SHouse;
    }
    
    public void setSHouse(java.lang.String SHouse) {
        this.SHouse = SHouse;
    }
    
    public java.lang.String getSCorps() {
        return SCorps;
    }
    
    public void setSCorps(java.lang.String SCorps) {
        this.SCorps = SCorps;
    }
    
    public java.lang.String getSBuilding() {
        return SBuilding;
    }
    
    public void setSBuilding(java.lang.String SBuilding) {
        this.SBuilding = SBuilding;
    }
    
    public java.lang.String getSFlat() {
        return SFlat;
    }
    
    public void setSFlat(java.lang.String SFlat) {
        this.SFlat = SFlat;
    }
    
    public java.lang.String getSOffice() {
        return SOffice;
    }
    
    public void setSOffice(java.lang.String SOffice) {
        this.SOffice = SOffice;
    }
    
    public java.lang.String getSStreetE() {
        return SStreetE;
    }
    
    public void setSStreetE(java.lang.String SStreetE) {
        this.SStreetE = SStreetE;
    }
    
    public java.lang.String getSCity() {
        return SCity;
    }
    
    public void setSCity(java.lang.String SCity) {
        this.SCity = SCity;
    }
    
    public java.lang.String getSRegion() {
        return SRegion;
    }
    
    public void setSRegion(java.lang.String SRegion) {
        this.SRegion = SRegion;
    }
    
    public java.lang.String getSAdrType() {
        return SAdrType;
    }
    
    public void setSAdrType(java.lang.String SAdrType) {
        this.SAdrType = SAdrType;
    }
    
    public java.lang.String getSAdrTypeName() {
        return SAdrTypeName;
    }
    
    public void setSAdrTypeName(java.lang.String SAdrTypeName) {
        this.SAdrTypeName = SAdrTypeName;
    }
}
