// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizicgate.bars.ws.jaxrpc;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;

public class XsbRemoteClientNameExtendedResult_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable  {
    private static final javax.xml.namespace.QName ns1_docID_QNAME = new QName("", "docID");
    private static final javax.xml.namespace.QName ns3_XsbDocID_TYPE_QNAME = new QName("http://common.xsb.webservices.bars.sbrf", "XsbDocID");
    private CombinedSerializer ns3_myXsbDocID_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_exceptionItems_QNAME = new QName("", "exceptionItems");
    private static final javax.xml.namespace.QName ns3_ArrayOfXsbExceptionItem_TYPE_QNAME = new QName("http://common.xsb.webservices.bars.sbrf", "ArrayOfXsbExceptionItem");
    private CombinedSerializer ns3_myArrayOfXsbExceptionItem_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_DOldNameBeg_QNAME = new QName("", "DOldNameBeg");
    private static final javax.xml.namespace.QName ns2_anyType_TYPE_QNAME = SchemaConstants.QNAME_TYPE_URTYPE;
    private CombinedSerializer ns2_ns2_anyType_TYPE_QNAME_Serializer;
    private static final javax.xml.namespace.QName ns1_DOldNameEnd_QNAME = new QName("", "DOldNameEnd");
    private static final javax.xml.namespace.QName ns1_SFName_QNAME = new QName("", "SFName");
    private static final javax.xml.namespace.QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns2_myns2_string__java_lang_String_String_Serializer;
    private static final javax.xml.namespace.QName ns1_SFNameOld_QNAME = new QName("", "SFNameOld");
    private static final javax.xml.namespace.QName ns1_SInn_QNAME = new QName("", "SInn");
    private static final javax.xml.namespace.QName ns1_SSName_QNAME = new QName("", "SSName");
    private static final javax.xml.namespace.QName ns1_SSNameOld_QNAME = new QName("", "SSNameOld");
    private static final javax.xml.namespace.QName ns1_SNumRegister_QNAME = new QName("", "SNumRegister");
    private static final javax.xml.namespace.QName ns1_DDateRegister_QNAME = new QName("", "DDateRegister");
    private static final javax.xml.namespace.QName ns1_SOkpo_QNAME = new QName("", "SOkpo");
    private static final javax.xml.namespace.QName ns1_SAddressRegister_QNAME = new QName("", "SAddressRegister");
    private static final javax.xml.namespace.QName ns1_SCountry_QNAME = new QName("", "SCountry");
    private static final javax.xml.namespace.QName ns1_SIndex_QNAME = new QName("", "SIndex");
    private static final javax.xml.namespace.QName ns1_SStreet_QNAME = new QName("", "SStreet");
    private static final javax.xml.namespace.QName ns1_SHouse_QNAME = new QName("", "SHouse");
    private static final javax.xml.namespace.QName ns1_SCorps_QNAME = new QName("", "SCorps");
    private static final javax.xml.namespace.QName ns1_SBuilding_QNAME = new QName("", "SBuilding");
    private static final javax.xml.namespace.QName ns1_SFlat_QNAME = new QName("", "SFlat");
    private static final javax.xml.namespace.QName ns1_SOffice_QNAME = new QName("", "SOffice");
    private static final javax.xml.namespace.QName ns1_SStreetE_QNAME = new QName("", "SStreetE");
    private static final javax.xml.namespace.QName ns1_SCity_QNAME = new QName("", "SCity");
    private static final javax.xml.namespace.QName ns1_SRegion_QNAME = new QName("", "SRegion");
    private static final javax.xml.namespace.QName ns1_SAdrType_QNAME = new QName("", "SAdrType");
    private static final javax.xml.namespace.QName ns1_SAdrTypeName_QNAME = new QName("", "SAdrTypeName");
    
    public XsbRemoteClientNameExtendedResult_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }
    
    public XsbRemoteClientNameExtendedResult_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }
    
    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns3_myXsbDocID_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.rssl.phizicgate.bars.ws.jaxrpc.XsbDocID.class, ns3_XsbDocID_TYPE_QNAME);
        ns3_myArrayOfXsbExceptionItem_LiteralSerializer = (CombinedSerializer)registry.getSerializer("", com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbExceptionItem.class, ns3_ArrayOfXsbExceptionItem_TYPE_QNAME);
        ns2_ns2_anyType_TYPE_QNAME_Serializer = (CombinedSerializer)registry.getSerializer("", javax.xml.soap.SOAPElement.class, ns2_anyType_TYPE_QNAME);
        ns2_myns2_string__java_lang_String_String_Serializer = (CombinedSerializer)registry.getSerializer("", java.lang.String.class, ns2_string_TYPE_QNAME);
    }
    
    public java.lang.Object doDeserialize(XMLReader reader,
        SOAPDeserializationContext context) throws java.lang.Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedResult instance = new com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedResult();
        java.lang.Object member=null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;
        
        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_docID_QNAME)) {
                member = ns3_myXsbDocID_LiteralSerializer.deserialize(ns1_docID_QNAME, reader, context);
                instance.setDocID((com.rssl.phizicgate.bars.ws.jaxrpc.XsbDocID)member);
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_exceptionItems_QNAME)) {
                member = ns3_myArrayOfXsbExceptionItem_LiteralSerializer.deserialize(ns1_exceptionItems_QNAME, reader, context);
                instance.setExceptionItems((com.rssl.phizicgate.bars.ws.jaxrpc.ArrayOfXsbExceptionItem)member);
                reader.nextElementContent();
            }
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_DOldNameBeg_QNAME)) {
                member = ns2_ns2_anyType_TYPE_QNAME_Serializer.deserialize(ns1_DOldNameBeg_QNAME, reader, context);
                instance.setDOldNameBeg((javax.xml.soap.SOAPElement)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_DOldNameBeg_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_DOldNameEnd_QNAME)) {
                member = ns2_ns2_anyType_TYPE_QNAME_Serializer.deserialize(ns1_DOldNameEnd_QNAME, reader, context);
                instance.setDOldNameEnd((javax.xml.soap.SOAPElement)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_DOldNameEnd_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SFName_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SFName_QNAME, reader, context);
                instance.setSFName((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SFName_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SFNameOld_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SFNameOld_QNAME, reader, context);
                instance.setSFNameOld((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SFNameOld_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SInn_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SInn_QNAME, reader, context);
                instance.setSInn((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SInn_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SSName_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SSName_QNAME, reader, context);
                instance.setSSName((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SSName_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SSNameOld_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SSNameOld_QNAME, reader, context);
                instance.setSSNameOld((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SSNameOld_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SNumRegister_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SNumRegister_QNAME, reader, context);
                instance.setSNumRegister((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SNumRegister_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_DDateRegister_QNAME)) {
                member = ns2_ns2_anyType_TYPE_QNAME_Serializer.deserialize(ns1_DDateRegister_QNAME, reader, context);
                instance.setDDateRegister((javax.xml.soap.SOAPElement)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_DDateRegister_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SOkpo_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SOkpo_QNAME, reader, context);
                instance.setSOkpo((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SOkpo_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SAddressRegister_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SAddressRegister_QNAME, reader, context);
                instance.setSAddressRegister((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SAddressRegister_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SCountry_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SCountry_QNAME, reader, context);
                instance.setSCountry((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SCountry_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SIndex_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SIndex_QNAME, reader, context);
                instance.setSIndex((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SIndex_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SStreet_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SStreet_QNAME, reader, context);
                instance.setSStreet((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SStreet_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SHouse_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SHouse_QNAME, reader, context);
                instance.setSHouse((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SHouse_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SCorps_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SCorps_QNAME, reader, context);
                instance.setSCorps((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SCorps_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SBuilding_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SBuilding_QNAME, reader, context);
                instance.setSBuilding((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SBuilding_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SFlat_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SFlat_QNAME, reader, context);
                instance.setSFlat((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SFlat_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SOffice_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SOffice_QNAME, reader, context);
                instance.setSOffice((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SOffice_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SStreetE_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SStreetE_QNAME, reader, context);
                instance.setSStreetE((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SStreetE_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SCity_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SCity_QNAME, reader, context);
                instance.setSCity((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SCity_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SRegion_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SRegion_QNAME, reader, context);
                instance.setSRegion((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SRegion_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SAdrType_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SAdrType_QNAME, reader, context);
                instance.setSAdrType((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SAdrType_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_SAdrTypeName_QNAME)) {
                member = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_SAdrTypeName_QNAME, reader, context);
                instance.setSAdrTypeName((java.lang.String)member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[] { ns1_SAdrTypeName_QNAME, reader.getName() });
            }
        }
        else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        
        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object)instance;
    }
    
    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedResult instance = (com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedResult)obj;
        
    }
    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedResult instance = (com.rssl.phizicgate.bars.ws.jaxrpc.XsbRemoteClientNameExtendedResult)obj;
        
        ns3_myXsbDocID_LiteralSerializer.serialize(instance.getDocID(), ns1_docID_QNAME, null, writer, context);
        ns3_myArrayOfXsbExceptionItem_LiteralSerializer.serialize(instance.getExceptionItems(), ns1_exceptionItems_QNAME, null, writer, context);
        ns2_ns2_anyType_TYPE_QNAME_Serializer.serialize(instance.getDOldNameBeg(), ns1_DOldNameBeg_QNAME, null, writer, context);
        ns2_ns2_anyType_TYPE_QNAME_Serializer.serialize(instance.getDOldNameEnd(), ns1_DOldNameEnd_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSFName(), ns1_SFName_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSFNameOld(), ns1_SFNameOld_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSInn(), ns1_SInn_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSSName(), ns1_SSName_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSSNameOld(), ns1_SSNameOld_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSNumRegister(), ns1_SNumRegister_QNAME, null, writer, context);
        ns2_ns2_anyType_TYPE_QNAME_Serializer.serialize(instance.getDDateRegister(), ns1_DDateRegister_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSOkpo(), ns1_SOkpo_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSAddressRegister(), ns1_SAddressRegister_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSCountry(), ns1_SCountry_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSIndex(), ns1_SIndex_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSStreet(), ns1_SStreet_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSHouse(), ns1_SHouse_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSCorps(), ns1_SCorps_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSBuilding(), ns1_SBuilding_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSFlat(), ns1_SFlat_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSOffice(), ns1_SOffice_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSStreetE(), ns1_SStreetE_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSCity(), ns1_SCity_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSRegion(), ns1_SRegion_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSAdrType(), ns1_SAdrType_QNAME, null, writer, context);
        ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getSAdrTypeName(), ns1_SAdrTypeName_QNAME, null, writer, context);
    }
}
