// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizic.web.gate.services.util;

import com.sun.xml.rpc.client.BasicService;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.soap.SOAPVersion;

import javax.xml.namespace.QName;
import javax.xml.rpc.encoding.Deserializer;
import javax.xml.rpc.encoding.Serializer;
import javax.xml.rpc.encoding.TypeMapping;
import javax.xml.rpc.encoding.TypeMappingRegistry;

public class GateInfoServiceImpl_SerializerRegistry implements SerializerConstants {
    public GateInfoServiceImpl_SerializerRegistry() {
    }
    
    public TypeMappingRegistry getRegistry() {
        
        TypeMappingRegistry registry = BasicService.createStandardTypeMappingRegistry();
        TypeMapping mapping12 = registry.getTypeMapping(SOAP12Constants.NS_SOAP_ENCODING);
        TypeMapping mapping = registry.getTypeMapping(SOAPConstants.NS_SOAP_ENCODING);
        TypeMapping mapping2 = registry.getTypeMapping("");
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "GateConfiguration");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateConfiguration_SOAPSerializer(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateConfiguration.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isRecipientExtedendAttributesAvailable");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isRecipientExtedendAttributesAvailable_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isRecipientExtedendAttributesAvailable_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isPaymentsRecallSupported");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPaymentsRecallSupported_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPaymentsRecallSupported_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "needTwoPhaseTransaction2");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_needTwoPhaseTransaction2_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_needTwoPhaseTransaction2_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isPaymentsRecallSupportedResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPaymentsRecallSupported_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPaymentsRecallSupported_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "Billing");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.Billing_SOAPSerializer(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.Billing.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "getAccountInputMode");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getAccountInputMode_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getAccountInputMode_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isPaymentCommissionAvailable");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPaymentCommissionAvailable_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPaymentCommissionAvailable_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "Code");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.Code_SOAPSerializer(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.Code.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "getUIDResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getUID_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getUID_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "getUID");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getUID_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getUID_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isRegistrationEnable");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isRegistrationEnable_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isRegistrationEnable_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "Office");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.Office_SOAPSerializer(type,
                ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.Office.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "needTwoPhaseTransaction");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_needTwoPhaseTransaction_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_needTwoPhaseTransaction_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isNeedChargeOffResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isNeedChargeOff_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isNeedChargeOff_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isPaymentCommissionAvailable2Response");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPaymentCommissionAvailable2_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPaymentCommissionAvailable2_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isOfficesHierarchySupported");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isOfficesHierarchySupported_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isOfficesHierarchySupported_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isPaymentCommissionAvailableResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPaymentCommissionAvailable_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPaymentCommissionAvailable_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "needTwoPhaseTransactionResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_needTwoPhaseTransaction_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_needTwoPhaseTransaction_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "getConfigurationResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getConfiguration_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getConfiguration_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isNeedAgrementCancellationResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isNeedAgrementCancellation_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isNeedAgrementCancellation_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isNeedAgrementCancellation");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isNeedAgrementCancellation_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isNeedAgrementCancellation_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isClientImportEnable");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isClientImportEnable_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isClientImportEnable_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isCurrencyRateAvailableResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isCurrencyRateAvailable_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isCurrencyRateAvailable_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isNeedChargeOff");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isNeedChargeOff_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isNeedChargeOff_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isPersonalRecipientAvailable");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPersonalRecipientAvailable_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPersonalRecipientAvailable_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isCalendarAvailableResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isCalendarAvailable_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isCalendarAvailable_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "getCardInputModeResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getCardInputMode_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getCardInputMode_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isClientImportEnableResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isClientImportEnable_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isClientImportEnable_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isRegistrationEnableResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isRegistrationEnable_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isRegistrationEnable_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "getAccountInputModeResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getAccountInputMode_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getAccountInputMode_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isRecipientExtedendAttributesAvailableResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isRecipientExtedendAttributesAvailable_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isRecipientExtedendAttributesAvailable_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isCurrencyRateAvailable");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isCurrencyRateAvailable_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isCurrencyRateAvailable_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "getCardInputMode");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getCardInputMode_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getCardInputMode_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isDelayedPaymentNeedSendResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isDelayedPaymentNeedSend_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isDelayedPaymentNeedSend_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isOfficesHierarchySupportedResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isOfficesHierarchySupported_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isOfficesHierarchySupported_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isCalendarAvailable");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isCalendarAvailable_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isCalendarAvailable_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isPaymentCommissionAvailable2");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPaymentCommissionAvailable2_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPaymentCommissionAvailable2_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isDelayedPaymentNeedSend");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isDelayedPaymentNeedSend_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isDelayedPaymentNeedSend_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "isPersonalRecipientAvailableResponse");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPersonalRecipientAvailable_ResponseStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_isPersonalRecipientAvailable_ResponseStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "getConfiguration");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getConfiguration_RequestStruct_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_getConfiguration_RequestStruct.class, type, serializer);
        }
        {
            QName type = new QName("http://generated.util.services.gate.web.phizic.rssl.com", "needTwoPhaseTransaction2Response");
            CombinedSerializer serializer = new com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_needTwoPhaseTransaction_ResponseStruct1_SOAPSerializer(type,
                DONT_ENCODE_TYPE, NULLABLE, SOAPConstants.NS_SOAP_ENCODING);
            serializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF, serializer, SOAPVersion.SOAP_11);
            registerSerializer(mapping,com.rssl.phizic.web.gate.services.util.generated.GateInfoService_PortType_needTwoPhaseTransaction_ResponseStruct1.class, type, serializer);
        }
        return registry;
    }
    
    private static void registerSerializer(TypeMapping mapping, java.lang.Class javaType, javax.xml.namespace.QName xmlType,
        Serializer ser) {
        mapping.register(javaType, xmlType, new SingletonSerializerFactory(ser),
            new SingletonDeserializerFactory((Deserializer)ser));
    }
    
}
