<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://generated.adapterinfo.multiblock.phizic.rssl.com" xmlns:sb="http://generated.adapterinfo.multiblock.phizic.rssl.com"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsdl="http://schemas.xmlsoap.org/wsdl/" name="ShopWService"
                  targetNamespace="http://generated.adapterinfo.multiblock.phizic.rssl.com">

    <wsdl:types>
        <xsd:schema xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://generated.adapterinfo.multiblock.phizic.rssl.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:include schemaLocation="AdapterInfo.xsd"/>
        </xsd:schema>
    </wsdl:types>
	<wsdl:message name="AdapterInfoRqMsg">
		<wsdl:part element="ns:AdapterInfoRq" name="parameters"/>
	</wsdl:message>
	<wsdl:message name="AdapterInfoRsMsg">
		<wsdl:part element="ns:AdapterInfoRs" name="result"/>
	</wsdl:message>
   	<wsdl:portType name="AdapterInfoService">
		<wsdl:operation name="AdapterInfo">
			<wsdl:input message="ns:AdapterInfoRqMsg"/>
			<wsdl:output message="ns:AdapterInfoRsMsg"/>
		</wsdl:operation>
	</wsdl:portType>
    <wsdl:binding name="AdapterInfoServiceSoapBinding" type="ns:AdapterInfoService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="AdapterInfo">
            <soap:operation style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
	<wsdl:service name="AdapterInfoServiceImpl">
		<wsdl:port binding="ns:AdapterInfoServiceSoapBinding" name="AdapterInfoServicePort">
			<soap:address location="http://localhost:8080/services/AdapterInfoServiceImpl"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>