CREATE TABLE NTFNTFY2_DBT
(
  ISCUR       INTEGER,
  BRANCH      INTEGER,
  OBJECTTYPE  INTEGER,
  OBJECTID    VARCHAR2(36),
  NOTIFYTYPE  INTEGER,
  NOTIFYDATE  DATE,
  NOTIFYTIME  DATE,
  NOTIFYOPER  INTEGER,
  REFERENC    INTEGER,
  RESERVED    VARCHAR2(192),
  OLDREST     NUMBER(19,4),
  NEWREST     NUMBER(19,4),
  IAPPLICATIONKIND INTEGER,
  APPLICATIONKEY VARCHAR2(30),
  SUMMA       NUMBER(19,4),
  OLDLIMIT    NUMBER(19,4),
  NEWLIMIT    NUMBER(19,4),
  OVERSUM     NUMBER(19,4),
  OVERTOTAL   NUMBER(19,4),
  MINREST     NUMBER(19,4),
  STATUS      VARCHAR2(10),
  ERROR       INTEGER
);

CREATE OR REPLACE TRIGGER NTFNTFY2_DBT_AINC
  BEFORE INSERT ON NTFNTFY2_DBT
  FOR EACH ROW
DECLARE
BEGIN
  SELECT NTFNTFY_DBT_SEQ.NEXTVAL
    INTO :NEW.REFERENC
  FROM DUAL;
END;
/

CREATE INDEX NTFNTFY2_DBT_IND0 ON NTFNTFY_DBT
(ISCUR, BRANCH, OBJECTTYPE, OBJECTID, NOTIFYTYPE);

CREATE INDEX NTFNTFY2_DBT_IND1 ON NTFNTFY_DBT
(ISCUR, BRANCH, OBJECTTYPE, OBJECTID, NOTIFYDATE, 
NOTIFYTIME);

CREATE UNIQUE INDEX NTFNTFY2_DBT_IND2 ON NTFNTFY_DBT
(REFERENC);