//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.10 at 01:13:02 PM MSD 
//


package com.rssl.phizic.web.config.view;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rssl.phizic.web.config.view package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
public class ObjectFactory
    extends com.rssl.phizic.web.config.view.impl.runtime.DefaultJAXBContextImpl
{

    private static java.util.HashMap defaultImplementations = new java.util.HashMap(16, 0.75F);
    private static java.util.HashMap rootTagMap = new java.util.HashMap();
    public final static com.rssl.phizic.web.config.view.impl.runtime.GrammarInfo grammarInfo = new com.rssl.phizic.web.config.view.impl.runtime.GrammarInfoImpl(rootTagMap, defaultImplementations, (com.rssl.phizic.web.config.view.ObjectFactory.class));
    public final static java.lang.Class version = (com.rssl.phizic.web.config.view.impl.JAXBVersion.class);

    static {
        defaultImplementations.put((com.rssl.phizic.web.config.view.ViewConfigRoot.class), "com.rssl.phizic.web.config.view.impl.ViewConfigRootImpl");
        defaultImplementations.put((com.rssl.phizic.web.config.view.ListDefinition.class), "com.rssl.phizic.web.config.view.impl.ListDefinitionImpl");
        defaultImplementations.put((com.rssl.phizic.web.config.view.ColumnType.class), "com.rssl.phizic.web.config.view.impl.ColumnTypeImpl");
        defaultImplementations.put((com.rssl.phizic.web.config.view.ViewConfigType.ListsType.class), "com.rssl.phizic.web.config.view.impl.ViewConfigTypeImpl.ListsTypeImpl");
        defaultImplementations.put((com.rssl.phizic.web.config.view.ViewConfigType.class), "com.rssl.phizic.web.config.view.impl.ViewConfigTypeImpl");
        rootTagMap.put(new javax.xml.namespace.QName("", "view-config"), (com.rssl.phizic.web.config.view.ViewConfigRoot.class));
    }

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rssl.phizic.web.config.view
     * 
     */
    public ObjectFactory() {
        super(grammarInfo);
    }

    /**
     * Create an instance of the specified Java content interface.
     * 
     * @param javaContentInterface
     *     the Class object of the javacontent interface to instantiate
     * @return
     *     a new instance
     * @throws JAXBException
     *     if an error occurs
     */
    public java.lang.Object newInstance(java.lang.Class javaContentInterface)
        throws javax.xml.bind.JAXBException
    {
        return super.newInstance(javaContentInterface);
    }

    /**
     * Get the specified property. This method can only be
     * used to get provider specific properties.
     * Attempting to get an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param name
     *     the name of the property to retrieve
     * @return
     *     the value of the requested property
     * @throws PropertyException
     *     when there is an error retrieving the given property or value
     */
    public java.lang.Object getProperty(java.lang.String name)
        throws javax.xml.bind.PropertyException
    {
        return super.getProperty(name);
    }

    /**
     * Set the specified property. This method can only be
     * used to set provider specific properties.
     * Attempting to set an undefined property will result
     * in a PropertyException being thrown.
     * 
     * @param value
     *     the value of the property to be set
     * @param name
     *     the name of the property to retrieve
     * @throws PropertyException
     *     when there is an error processing the given property or value
     */
    public void setProperty(java.lang.String name, java.lang.Object value)
        throws javax.xml.bind.PropertyException
    {
        super.setProperty(name, value);
    }

    /**
     * Create an instance of ViewConfigRoot
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.rssl.phizic.web.config.view.ViewConfigRoot createViewConfigRoot()
        throws javax.xml.bind.JAXBException
    {
        return new com.rssl.phizic.web.config.view.impl.ViewConfigRootImpl();
    }

    /**
     * Create an instance of ListDefinition
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.rssl.phizic.web.config.view.ListDefinition createListDefinition()
        throws javax.xml.bind.JAXBException
    {
        return new com.rssl.phizic.web.config.view.impl.ListDefinitionImpl();
    }

    /**
     * Create an instance of ColumnType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.rssl.phizic.web.config.view.ColumnType createColumnType()
        throws javax.xml.bind.JAXBException
    {
        return new com.rssl.phizic.web.config.view.impl.ColumnTypeImpl();
    }

    /**
     * Create an instance of ViewConfigTypeListsType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.rssl.phizic.web.config.view.ViewConfigType.ListsType createViewConfigTypeListsType()
        throws javax.xml.bind.JAXBException
    {
        return new com.rssl.phizic.web.config.view.impl.ViewConfigTypeImpl.ListsTypeImpl();
    }

    /**
     * Create an instance of ViewConfigType
     * 
     * @throws JAXBException
     *     if an error occurs
     */
    public com.rssl.phizic.web.config.view.ViewConfigType createViewConfigType()
        throws javax.xml.bind.JAXBException
    {
        return new com.rssl.phizic.web.config.view.impl.ViewConfigTypeImpl();
    }

}
