//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.5-b16-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2007.08.10 at 01:13:02 PM MSD 
//


package com.rssl.phizic.web.config.view;


/**
 * Java content class for anonymous complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/zzz/view/view-config.xsd line 20)
 * <p>
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="lists" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="list" type="{}ListDefinition" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ViewConfigType {


    /**
     * Gets the value of the lists property.
     * 
     * @return
     *     possible object is
     *     {@link com.rssl.phizic.web.config.view.ViewConfigType.ListsType}
     */
    com.rssl.phizic.web.config.view.ViewConfigType.ListsType getLists();

    /**
     * Sets the value of the lists property.
     * 
     * @param value
     *     allowed object is
     *     {@link com.rssl.phizic.web.config.view.ViewConfigType.ListsType}
     */
    void setLists(com.rssl.phizic.web.config.view.ViewConfigType.ListsType value);


    /**
     * Java content class for anonymous complex type.
     * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/zzz/view/view-config.xsd line 23)
     * <p>
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="list" type="{}ListDefinition" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     */
    public interface ListsType {


        /**
         * Gets the value of the ListDefinitions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the ListDefinitions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getListDefinitions().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link com.rssl.phizic.web.config.view.ListDefinition}
         * 
         */
        java.util.List getListDefinitions();

    }

}
