// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizic.web.gate.services.cache;

public interface CacheService extends java.rmi.Remote {
    public void clearAccountCache(com.rssl.phizic.web.gate.services.cache.generated.Account account_1) throws 
         java.rmi.RemoteException;
    public void clearCardCache(com.rssl.phizic.web.gate.services.cache.generated.Card card_1) throws 
         java.rmi.RemoteException;
    public void clearClientCache(com.rssl.phizic.web.gate.services.cache.generated.Client client_1) throws 
         java.rmi.RemoteException;
    public void clearCurrencyRateCache(com.rssl.phizic.web.gate.services.cache.generated.CurrencyRate currencyRate_1, com.rssl.phizic.web.gate.services.cache.generated.Office office_2) throws 
         java.rmi.RemoteException;
    public void clearDepositCache(com.rssl.phizic.web.gate.services.cache.generated.Deposit deposit_1) throws 
         java.rmi.RemoteException;
}
