<?xml version="1.0" encoding="UTF-8"?>

<definitions name="CommunalServiceService" targetNamespace="http://jaxrpc.generated.cpfl.webgate.test.phizic.rssl.com" xmlns:tns="http://jaxrpc.generated.cpfl.webgate.test.phizic.rssl.com" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types/>
  <message name="CommunalServicePT_sendMessage">
    <part name="String_1" type="xsd:string"/></message>
  <message name="CommunalServicePT_sendMessageResponse">
    <part name="result" type="xsd:string"/></message>
  <portType name="CommunalServicePT">
    <operation name="sendMessage" parameterOrder="String_1">
      <input message="tns:CommunalServicePT_sendMessage"/>
      <output message="tns:CommunalServicePT_sendMessageResponse"/></operation></portType>
  <binding name="CommunalServicePTBinding" type="tns:CommunalServicePT">
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="rpc"/>
    <operation name="sendMessage">
      <soap:operation soapAction=""/>
      <input>
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="encoded" namespace="http://jaxrpc.generated.cpfl.webgate.test.phizic.rssl.com"/></input>
      <output>
        <soap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" use="encoded" namespace="http://jaxrpc.generated.cpfl.webgate.test.phizic.rssl.com"/></output></operation></binding>
  <service name="CommunalServiceService">
    <port name="CommunalServicePTPort" binding="tns:CommunalServicePTBinding">
      <soap:address location="http://localhost:8080/services/CommunalServiceService"/></port></service></definitions>
