<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://generated.pfr.esberiblistener.ws.phizic.rssl.com" xmlns:sb="http://generated.pfr.esberiblistener.ws.phizic.rssl.com" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="PfrWService" targetNamespace="http://generated.pfr.esberiblistener.ws.phizic.rssl.com">

    <wsdl:types>
        <xsd:schema xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" targetNamespace="http://generated.pfr.esberiblistener.ws.phizic.rssl.com" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:include schemaLocation="pfrDone.xsd"/>
        </xsd:schema>
    </wsdl:types>
	<wsdl:message name="PfrDoneRqMsg">
		<wsdl:part element="ns:PfrDoneRq" name="parameters"/>
	</wsdl:message>
	<wsdl:message name="PfrDoneRsMsg">
		<wsdl:part element="ns:PfrDoneRs" name="result"/>
	</wsdl:message>
	<wsdl:portType name="PfrDoneService">
		<wsdl:operation name="pfrDone">
			<wsdl:input message="ns:PfrDoneRqMsg"/>
			<wsdl:output message="ns:PfrDoneRsMsg"/>
		</wsdl:operation>
	</wsdl:portType>
    <wsdl:binding name="PfrDoneServiceSoapBinding" type="ns:PfrDoneService">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="pfrDone">
            <soap:operation style="document"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
	<wsdl:service name="PfrDoneServiceImpl">
		<wsdl:port binding="ns:PfrDoneServiceSoapBinding" name="PfrDoneServicePort">
			<soap:address location="http://localhost:8080/services/PfrDoneServiceImpl"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>