//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.27 at 11:54:47 AM MSK 
//

package com.rssl.phizic.business.ermb.sms.config;

import java.util.List;
import javax.xml.bind.annotation.*;

/**
 * Бин для конвертации в/из xml
 */
@XmlRootElement(name="config")
@XmlType(name = "Config")
@XmlAccessorType(XmlAccessType.NONE)
class SmsConfigBean
{
	@XmlElement(name = "dublicate-filter")
	private DublicateFilter dublicateFilter;

	@XmlType(name = "DublicateFilterType")
	@XmlAccessorType(XmlAccessType.NONE)
	static class DublicateFilter
	{
        @XmlElement(name = "dublicate-expire-interval")
        private int value;

        public int getValue()
        {
            return value;
        }

		public void setValue(int value)
		{
			this.value = value;
		}
	}

	@XmlElement(name = "preprocessor")
	private PreprocessorBean preprocessor;

	PreprocessorBean getPreprocessor()
	{
		return preprocessor;
	}

	void setPreprocessor(PreprocessorBean preprocessor)
	{
		this.preprocessor = preprocessor;
	}

	@XmlElementWrapper(name = "commands", required = true)
    @XmlElement(name = "command")
    private List<CommandDefinitionBean> commands;

    List<CommandDefinitionBean> getCommands()
    {
	    //noinspection ReturnOfCollectionOrArrayField
	    return commands;
    }

	void setCommands(List<CommandDefinitionBean> commands)
	{
		//noinspection AssignmentToCollectionOrArrayFieldFromParameter
		this.commands = commands;
	}

	public DublicateFilter getDublicateFilter()
	{
		return dublicateFilter;
	}

	public void setDublicateFilter(DublicateFilter dublicateFilter)
	{
		this.dublicateFilter = dublicateFilter;
	}

	@XmlElement(name = "incomplete-payments-remover", required = true)
	private IncompletePaymentsRemover incompletePaymentsRemover;

	@XmlType(name = "IncompletePaymentsRemover")
	@XmlAccessorType(XmlAccessType.NONE)
	static class IncompletePaymentsRemover
	{
        @XmlElement(name = "incomplete-payments-expire-interval", required = true)
        private int value;

        public int getValue()
        {
            return value;
        }

		public void setValue(int value)
		{
			this.value = value;
		}
	}

	IncompletePaymentsRemover getIncompletePaymentsRemover()
	{
		return incompletePaymentsRemover;
	}

	void setIncompletePaymentsRemover(IncompletePaymentsRemover incompletePaymentsRemover)
	{
		this.incompletePaymentsRemover = incompletePaymentsRemover;
	}
}
