import rcw, rsd, deprintr;
import "rt_ib_xml.mac";



// ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
// â§ë¢ ®â«®¦¥­­®£® ¤®ªã¬¥­â 
// ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
class(cBaseDeposit) 
    cRecallDocument( inXml, outXml ) 

  var outXML_cur;
  var psdepdoc = TBFile( "psdepdoc.dbt",  "w", 0, NULL, "sbbank.def" );

  var appKind, appKey;

/* 
    ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
      ˆ‘•„›… „€›…  
    ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

«¥¬¥­â á®®¡é¥­¨ï	   ’¨¯		   Š®¬¬¥­â à¨©	                           Šà â­®áâì
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
request			
ÃÄid                       string(32)      ˆ¤¥­â¨ä¨ª â®à § ¯à®á  ¢ á¨áâ¥¬¥  ˆŠ”‹	
ÀÄrecallDocument_q                         ‡ ¯à®á ¯® ®¤­®¬ã ¢¨¤ã ¢ª« ¤             [0..a]
  ÀÄdocument                               ˆ¤¥­â¨ä¨ª â®à ¤®ªã¬¥­â 
    ÃÄapplicationKind      int             ˆ¤¥­â¨ä¨ª â®à ¤®ªã¬¥­â  
    ÀÄapplicationKey       string(29)      ˆ¤¥­â¨ä¨ª â®à ¤®ªã¬¥­â 


    ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
          ’‚…’
    ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
«¥¬¥­â á®®¡é¥­¨ï	’¨¯		Š®¬¬¥­â à¨©
ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÅÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
response			
ÃÄparentId              string(32)      ˆ¤¥­â¨ä¨ª â®à § ¯à®á  ¢ á¨áâ¥¬¥  ˆŠ”‹	
ÃÄid                    string(32)      ˆ¤¥­â¨ä¨ª â®à ®â¢¥â 	
ÀÄrecallDocument_a
  ÃÄerrorCode           int             Š®¤ ®è¨¡ª¨
  ÃÄerrorText           string(80)      ’¥ªáâ ®è¨¡ª¨
  ÃÄapplicationKind     int             ˆ¤¥­â¨ä¨ª â®à ¤®ªã¬¥­â  
  ÀÄapplicationKey      string(29)      ˆ¤¥­â¨ä¨ª â®à ¤®ªã¬¥­â 

*/

  // ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  
  // ”®à¬¨àã¥¬ ¢ëå®¤­®© XML
  // ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
  private macro createDateTag( stat, errMes )
    var nodeTemp;
    if ( stat == null )
      stat = 0;
    end;
     
    nodeTemp = nodeAnswer.appendChild( outXML_cur.createNode(1, "document", "") ); 
   
    node = nodeTemp.appendChild( outXML_cur.createNode(1, "errorCode", "") ); 
    node.text = stat;

    if ( stat != 0 )
      if ( errMes == null )
        errMes = getErrorString( stat );
      end;

      node = nodeTemp.appendChild( outXML_cur.createNode(1, "errorText", "") ); 
      node.text = errMes;
    end;

    node = nodeTemp.appendChild( outXML_cur.createNode(1, "applicationKind", "") ); 
    node.text = appKind;
                
    node = nodeTemp.appendChild( outXML_cur.createNode(1, "applicationKey", "") ); 
    node.text = appKey;

  end;

// ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
// ¡à ¡ âë¢ ¥¬ ¤ ­­ë¥
// ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
  macro make  

    var stat = false;
    var cmd_find, rs_find, cmd_del;
    var flag;

    cmd_find = RsdCommand("select t_flags2 fl " +
                            "from dpsdepdoc_dbt " +
                           "where t_iapplicationkind = ? " +
                             "and t_applicationkey = ? ");
    cmd_find.addParam( "appKind", RSDBP_IN ); cmd_find.value( "appKind" ) = appKind;
    cmd_find.addParam( "appKey",  RSDBP_IN ); cmd_find.value( "appKey" )  = appKey;
    
    cmd_find.execute;

    rs_find = RsdRecordSet( cmd_find );

    if( rs_find.moveNext )
      flag = rs_find.value( "fl" );
      if ( flag == 4 )
        cmd_del = RsdCommand("delete dpsdepdoc_dbt " +
                              "where t_iapplicationkind = ? " +
                                "and t_applicationkey = ? ");
        cmd_del.addParam( "appKind", RSDBP_IN ); cmd_del.value( "appKind" ) = appKind;
        cmd_del.addParam( "appKey",  RSDBP_IN ); cmd_del.value( "appKey" )  = appKey;
   
        stat = cmd_del.execute;
        createDateTag( stat );

      else
        createDateTag( -1, "„®ªã¬¥­â ¯®à®¦¤¥­ ­¥ ˆŠ”‹. â§ë¢ § ¯à¥é¥­." );
      end;
    else
      createDateTag( -1, "â«®¦¥­­ë© ¤®ªã¬¥­â ­¥ ­ ©¤¥­." );
    end;


  end; //make


  // ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ  
  // ‡ ¯ãáâª ¯à®æ¥¤ãàë
  // ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
  macro start( inXml, outXml ) 
    var stat = 0;
    var nodeRecallDocument, nodeDocument, nodeTemp;

    outXML_cur = outXml;    
    if(not outXml_cur )
      outXml_cur = CreateXMLObject();
      if(not outXml_cur) return; end;

      nodeRecallDocument = inXml.documentElement.selectSingleNode( "//" + NameInputTag );
      CreateBeginTag( outXml_cur );

      nodeDocument = nodeRecallDocument.firstChild;
      
      while( nodeDocument )
        if ( nodeDocument.nodeName == "document" )

          nodeTemp = nodeDocument.firstChild();
          while ( nodeTemp )
            if   ( nodeTemp.nodeName == "applicationKind" ) 
              appKind = int( nodeTemp.text );
            elif ( nodeTemp.nodeName == "applicationKey" ) 
              appKey  = string( nodeTemp.text );
            end; 
            nodeTemp = nodeTemp.nextSibling();
          end; // while ( nodeTemp )

          stat = ProcessTrn( 0, R2M ( this, "make") );
          
        end;// ( nodeDocument.nodeName == "document" )
        nodeDocument = nodeDocument.nextSibling();
      end; // while( nodeDocument )

    end;  

    return outXml_cur;
  end;//start( inXml, outXml ) 



end;// class(cBaseDeposit) cRecallDocument( inXml, outXml ) 



// ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
// â§ë¢ ®â«®¦¥­­®£® ¤®ªã¬¥­â 
// ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
macro recallDocument( inXml, outXml ) 

  var t = cRecallDocument;
  outXml = t.start( inXml, outXml );

  SetParm(1, outXml);
end;
