// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizic.web.gate.services.clients;


public class Office {
    protected java.lang.String BIC;
    protected java.lang.String address;
    protected com.rssl.phizic.web.gate.services.clients.generated.Code code;
    protected java.lang.String name;
    protected java.lang.String postIndex;
    protected java.lang.String sbidnt;
    protected java.lang.String synchKey;
    protected java.lang.String telephone;
    
    public Office() {
    }
    
    public Office(java.lang.String BIC, java.lang.String address, com.rssl.phizic.web.gate.services.clients.generated.Code code, java.lang.String name, java.lang.String postIndex, java.lang.String sbidnt, java.lang.String synchKey, java.lang.String telephone) {
        this.BIC = BIC;
        this.address = address;
        this.code = code;
        this.name = name;
        this.postIndex = postIndex;
        this.sbidnt = sbidnt;
        this.synchKey = synchKey;
        this.telephone = telephone;
    }
    
    public java.lang.String getBIC() {
        return BIC;
    }
    
    public void setBIC(java.lang.String BIC) {
        this.BIC = BIC;
    }
    
    public java.lang.String getAddress() {
        return address;
    }
    
    public void setAddress(java.lang.String address) {
        this.address = address;
    }
    
    public com.rssl.phizic.web.gate.services.clients.generated.Code getCode() {
        return code;
    }
    
    public void setCode(com.rssl.phizic.web.gate.services.clients.generated.Code code) {
        this.code = code;
    }
    
    public java.lang.String getName() {
        return name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }
    
    public java.lang.String getPostIndex() {
        return postIndex;
    }
    
    public void setPostIndex(java.lang.String postIndex) {
        this.postIndex = postIndex;
    }
    
    public java.lang.String getSbidnt() {
        return sbidnt;
    }
    
    public void setSbidnt(java.lang.String sbidnt) {
        this.sbidnt = sbidnt;
    }
    
    public java.lang.String getSynchKey() {
        return synchKey;
    }
    
    public void setSynchKey(java.lang.String synchKey) {
        this.synchKey = synchKey;
    }
    
    public java.lang.String getTelephone() {
        return telephone;
    }
    
    public void setTelephone(java.lang.String telephone) {
        this.telephone = telephone;
    }
}
