// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.rssl.phizic.web.gate.services.clients;

public interface RegistartionClientService_PortType extends java.rmi.Remote {
    public CancelationCallBackImpl cancellation(com.rssl.phizic.web.gate.services.clients.generated.Client client_1, java.lang.String string_2, java.util.Calendar calendar_3, java.lang.String string_4, java.lang.String string_5) throws
         java.rmi.RemoteException;
    public void register(com.rssl.phizic.web.gate.services.clients.generated.Office office_1, java.lang.String string_2) throws 
         java.rmi.RemoteException;
    public void update(com.rssl.phizic.web.gate.services.clients.generated.Office office_1, java.lang.String string_2) throws 
         java.rmi.RemoteException;
}
