--Проносим изменеия в ЦСА Админ
insert into CARD_OPERATION_CATEGORIES( ID,   NAME,   INCOME,   CASH,   CASHLESS,   LOGIN_ID,   EXTERNALID,   ALLOW_INCOMPATIBLE_OPERATIONS,   IS_DEFAULT,   VISIBLE,   FOR_INTERNAL_OPERATIONS,   IS_TRANSFER,   ID_IN_MAPI,   COLOR,   UUID )   
select 
	S_CARD_OPERATION_CATEGORIES.nextval,   NAME,   INCOME,   CASH,   CASHLESS,   LOGIN_ID,   EXTERNALID,   ALLOW_INCOMPATIBLE_OPERATIONS,   IS_DEFAULT,   VISIBLE,   FOR_INTERNAL_OPERATIONS,   IS_TRANSFER,   ID_IN_MAPI,   COLOR,   UUID 
from CARD_OPERATION_CATEGORIES@CSAADMIN_LINK where nvl(LOGIN_ID, -1)=-1
/

insert into MERCHANT_CATEGORY_CODES ( CODE, INCOME_OPERATION_CATEGORY_ID, OUTCOME_OPERATION_CATEGORY_ID) 
	select CODE, INCOME_OPERATION_CATEGORY_ID, OUTCOME_OPERATION_CATEGORY_ID from MERCHANT_CATEGORY_CODES@CSAADMIN_LINK
/	

insert into CARD_OPERATION_TYPES ( CODE, CASH ) 
	select CODE, CASH from CARD_OPERATION_TYPES@CSAADMIN_LINK
/	

insert into CONTACT_CENTER_AREAS ( ID, UUID, AREA_NAME ) 
	select ID, UUID, AREA_NAME from CONTACT_CENTER_AREAS@CSAADMIN_LINK
/	

insert into C_CENTER_AREAS_DEPARTMENTS ( C_C_AREA_ID, TB ) 
	select C_C_AREA_ID, TB from C_CENTER_AREAS_DEPARTMENTS@CSAADMIN_LINK
/	

insert into MAIL_SUBJECTS ( ID, UUID, DESCRIPTION )
	select ID, UUID, DESCRIPTION from MAIL_SUBJECTS@CSAADMIN_LINK
/

update ACCESSSCHEMES@CSAADMIN_LINK SET MAIL_MANAGEMENT='1' WHERE ID = ( select EXTERNAL_ID from ACCESSSCHEMES where MAIL_MANAGEMENT = '1' and EXTERNAL_ID is not null )
/